### ISSUE TITLE
The plugin hides duty names in the Duty Finder window

### ISSUE THREAD

**Issue by OffworldMiningCompany** [MidoriKami/DailyDuty#100]
The plugin hides duty names in the Duty Finder window, except for those that are overridden by enabling Duty Finder Overlay. Disabling Duty Roulette doesn't change this.

**Comment by MidoriKami** [comment]
Show picture.

**Comment by MidoriKami** [comment]
Found the likely cause, will fix in next release.

**Comment by OffworldMiningCompany** [comment]
That was an impressively quick response!

**Comment by MidoriKami** [comment]
Fixed in acd03d27647ee6c7fa92326556f5bc4a13e8fd14
