### ISSUE TITLE
Island Sanctuary Dailies?

### ISSUE THREAD

**Issue by bonekid** [MidoriKami/DailyDuty#101]
Are there any plans to add the daily Island Sanctuary tasks to the plugin? I've read through the pinned issue saying that you have implemented everything so does that mean you are not planning to add Island Sanctuary?

**Comment by MidoriKami** [comment]
Island Sanctuary does not fall under a "daily" nor a "weekly" task, nor does it have a clear "You have completed this task" condition. It will not be added to DailyDuty.

**Comment by eaganlai** [comment]
How about a weekly reset timer that is manually marked as finished by the user? It sounds dumb but it still serves its function as a weekly reminder perfectly.
It fits the plugin as it is something occurs weekly where players need to visit their island at least once a week to set the workshop schedule so others have made the same request over and over. Totally understand there is not a completed status for the chore as you can undo the schedule and have not enough allocated resources even if you filled the schedule. But having an in-game weekly reminder over the requiring chores in DD would be nice, as it is something needs doing every week.

**Comment by MidoriKami** [comment]
No.
