### ISSUE TITLE
Suggestion: Add amounts to Challenge Log items

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [MidoriKami/DailyDuty#102]
When the settings for "Use Long Label" on Challenge Log, it shows the names of the tracked Challenges. Would it be possible to add the amount/needed amount to that label?

IE. Feeling Lucky would read something like "Feeling Lucky (2/3)" after you've done two dungeons.

**Comment by MidoriKami** [comment]
No. I do not have access to status information for Challenge Log only complete/incomplete.

Additionally displaying long labels has been removed in DailyDuty v4
