### ISSUE TITLE
Teleporter integration failed

### ISSUE THREAD

**Issue by Altair31** [MidoriKami/DailyDuty#103]
I once had DailyDuty working well with Teleporter plugin but since some weeks, it stopped working asking me to install Teleporter.
Of course Teleporter is installed and active.
I tried to revove them both and reinstall without success.

**Comment by MidoriKami** [comment]
It's a localization bug, if you use English it'll work as expected. This is fixed in DailyDuty v4 that will be releasing to public stable in the next week.

**Comment by MidoriKami** [comment]
This should be working correctly for all languages now as of DailyDuty Version 4.0.0.0

**Comment by Altair31** [comment]
Confirmed as fixed
