### ISSUE TITLE
Version 4 incorrectly tracks Treasure Map and Mini Cactpot status across characters

### ISSUE THREAD

**Issue by novaminor** [MidoriKami/DailyDuty#105]
Hello, thank you for making this plugin! I rely on it quite a bit to track tasks across 2 characters on the same service account.

After reconfiguring the new version of the plugin on my 1st character and completing all the daily tasks, I then moved to my 2nd character where I slightly tweaked the config but noticed it was already making the treasure map and mini cactpot as complete even though I had not completed them on the 2nd character yet:
![DD_tmap](https://user-images.githubusercontent.com/39936136/230160931-ec794985-e177-496e-a5c8-d6f0fc9f58cc.png)

Let me know if I can provide any more information to help troubleshoot.

**Comment by MidoriKami** [comment]
Did you copy any files between characters?

**Comment by novaminor** [comment]
I didn't personally copy any files but I do use Character Data Sync plugin which I assume is coping files between them. Can I assume that to be the root cause of the problem then?

**Comment by MidoriKami** [comment]
I am unable to reproduce this issue.

Let me know if it occurs again tomorrow.

**Comment by novaminor** [comment]
Ok copy, I'll report back tomorrow. Thanks for looking!

**Comment by novaminor** [comment]
Hi, after the daily reset and completing tasks on my first character it looks like everything is reporting accurately today on my second character.
