### ISSUE TITLE
Bring Back Custom Colors pls

### ISSUE THREAD

**Issue by killburns911** [MidoriKami/DailyDuty#109]
Hellow,

![image](https://user-images.githubusercontent.com/15521962/230500361-c48c73de-3d18-4512-be23-d79d6f309f33.png)

Could you push new version with Colors ?
Yellow = Completed ( Weekly )
Green = Clear
Red = Must Do

**Comment by QueenLinuxGlitch** [comment]
Dev lost a lot of respect for how they handled this

**Comment by QueenLinuxGlitch** [comment]
Use SimpleTweaks Plugin, they pushed the overlay to another plugin

**Comment by killburns911** [comment]
> Use SimpleTweaks Plugin, they pushed the overlay to another plugin

Thanks, but now it's all red, (or green) i want to specify wich duty i want to do

**Comment by Andreyf20** [comment]
@killburns911 i'm using simple tweaks and it is working for me, completed roulettes are green, not done yet roulettes are red.

![image](https://user-images.githubusercontent.com/28910336/230556673-6e8caf81-3243-450f-ac9b-95e2b06e4c3f.png)

**Comment by killburns911** [comment]
> @killburns911 i'm using SimpleTweaks instead of DailyDuty and it is working for me, completed roulettes are green, not done yet roulettes are red.
> 
> ![image](https://user-images.githubusercontent.com/28910336/230556673-6e8caf81-3243-450f-ac9b-95e2b06e4c3f.png)

Yes, But, if i wish do specific duty ( like expert, raid alliance, just for win matérias with special bonus, mentor ect... ) 
the previous version have the option :'( 
And for weekly the expert duty appears in orange/yellow ( default color )

**Comment by MarcoMajoor** [comment]
Didn't this plugin place the Wondrous Tails icons next to eligible duties? That's gone as well (And not part of SimpleTweaks as far as I can tell)

**Comment by QueenLinuxGlitch** [comment]
I agree,, not being able to customize it means they pushed their OWN code and nerfed it. SMH

**Comment by MidoriKami** [comment]
https://github.com/Caraxi/SimpleTweaksPlugin/pull/552

The feature has been finished in SimpleTweaks and is awaiting a SimpleTweaks update.
Maybe next time before you start whining, check your entitlement, I provide plugins for free in my free time.

All my plugins could disappear tomorrow if I chose.
