### ISSUE TITLE
Timers removed

### ISSUE THREAD

**Issue by QueenLinuxGlitch** [MidoriKami/DailyDuty#110]
Only inconvenient because your docs still say you have them plus you did not add the timer removal to your commit history. Sloppy

**Comment by QueenLinuxGlitch** [comment]
AND you removed highlighting incomplete duty finders? christ

**Comment by ScootyBootyff** [comment]
please bring this feature back

**Comment by MidoriKami** [comment]
This is not up for debate.

I will update the github documentation when I have time.
