### ISSUE TITLE
Daily Duty not rendering todo list; config window rendering incorrectly

### ISSUE THREAD

**Issue by jguluarte** [MidoriKami/DailyDuty#112]
[System Info]
- 4k, playing on a 64" TV, 
- Using 36pt font size in Dalamud

[Error 1 -- Todo Window not rendering]
Since the patch, the daily todo list isn't rendering. I tried all of the following:
* `/dd todo toggle`
* `/dd todo hide` followed by `/dd todo show`
* `/dd todo show` repeatedly

[Error 2 -- Configuration window renders overlapping itself, anchored to left side]
Wnen I type `/dd` to open the config window, in the `Modular Configuration` tab, everything has compressed into the far left column. This behavior is the same regardless of the Dalamud font setting

**Comment by MidoriKami** [comment]
Can you attach a copy of `Todo.config.json` ?

Can you attach an image of error 2 ?

**Comment by jguluarte** [comment]
662501-e08d0d2d-ce97-4395-8623-b3c12f9a0854.jpg)

**Comment by jguluarte** [comment]
(pressed the wrong button)

**Comment by MidoriKami** [comment]
Ah, so the module selection section has this faint vertical bar you can click and drag that to make the selection section bigger or smaller.

You can find character configs in `%appdat%\XIVLauncher\pluginConfigs\DailyDuty`

**Comment by MidoriKami** [comment]
Additional information has been requested if it is not received in a timely manner this issue will be closed.

**Comment by jguluarte** [comment]
Sorry for the delay, work was a nightmare yesterday. 

There is no `Todo.config.json` in any of the folders within AppData related to `XIVLauncher` and `DailyDuty`.

I do see some config json files using other names, found in `\AppData\Roaming\XIVLauncher\pluginConfigs\DailyDuty`. I zipped the entire folder [here](https://github.com/MidoriKami/DailyDuty/files/11183916/DailyDuty.zip).

**Comment by MidoriKami** [comment]
Ah okay I think I see the issue, the Todo List is configured correctly and is displaying, but because you have no modules enabled there's nothing to show. Enable some modules, and incomplete ones will display in the todo list.

https://user-images.githubusercontent.com/9083275/230739197-704b69d1-53ce-43f5-a53b-530ab49259a6.mp4

**Comment by jguluarte** [comment]
Hmmm. That's strange. I definitely had them before, could they have been overwritten somehow with the update this week?
