### ISSUE TITLE
Exclude duties from Complete When Tomecapped

### ISSUE THREAD

**Issue by novaminor** [MidoriKami/DailyDuty#113]
Hello, is it possible to exclude duties from the Complete When Tomecapped option in the Module Configuration for Duty Roulettes? My use case is tracking the Expert Roulette to cap tomes each week but I also want to track the Frontline roulette for the PVP series and job XP for each day regardless if my tomes are capped or not.

Thank you for considering this change.

**Comment by MidoriKami** [comment]
That's reasonable. Will do.

**Comment by MidoriKami** [comment]
After digging into this some more, I will not be implementing this feature.

**Comment by novaminor** [comment]
Ok, copy. Would you accept a PR for this feature if I can figure out how to get it working?

**Comment by MidoriKami** [comment]
It is unlikely that I would accept a PR for that feature as it would overcomplicate the UI.
if it is done in an elegant way I would be willing to merge it.
