### ISSUE TITLE
Bring Timers Back! (Pretty please, maybe?)

### ISSUE THREAD

**Issue by AustinZM** [MidoriKami/DailyDuty#114]
I noticed the timers feature was cut from the plugin after updating recently. I do like what you've done with the todo UI but I really liked being able to see the reset timers to know how much I could procrastinate. (Okay, maybe it was a bad thing.. >_>) Would it be possible to bring back the timers in a clean way just so that information could be easily available?

I did see that there was some kind of problem with the timers in the Discord help forum which was causing you a headache which I assume was the reason for removing it entirely. Could it be an informational UI only and not hook with the actual DD list itself?

**Comment by MidoriKami** [comment]
Timers will not be returning.
