### ISSUE TITLE
Option to hide challenge log data

### ISSUE THREAD

**Issue by AustinZM** [MidoriKami/DailyDuty#115]
Would it be possible to add an option to only show challenge log data in the Module Data tab based on what you have selected in the Module Configuration tab? It's rather difficult to fully keep track of the tasks you want to do since it shows every challenge log task by default.

**Comment by MidoriKami** [comment]
The data tab is intended to show **all** data that DailyDuty has for a given module.
It's supposed to show **all** data for a module, not just tracked data.
It's not meant to be a checklist.

**Comment by AustinZM** [comment]
In that case are you planning on adding some sort of checklist feature in the future? Some parts of the plugin are rather user unfriendly at the moment as is.

**Comment by MidoriKami** [comment]
No.

**Comment by AustinZM** [comment]
I'm a bit confused why you see it as a non-issue with how unfunctional the challenge log portion of it is compared to how it could be. But hey, it's your project, go ahead. I'm sorry you've had so many negative experiences lately but you aren't being rather friendly towards people, to be honest.
