### ISSUE TITLE
Unable to update to v4.0.0.6

### ISSUE THREAD

**Issue by 99bluerabbit** [MidoriKami/DailyDuty#117]
Searched through issues and didnt see the issue listed.

When i try to auto-update to v4.0.0.6 it fails without any errorcode
When i try to manually update it also mentioned that it fails and to restart the game (which has been attempted) or to contact author (which is now being attempted)

I look forward to your assistance.

**Comment by MidoriKami** [comment]
Please upload yourm`dalamud.log` file here

**Comment by 99bluerabbit** [comment]
Thanks, here you go
[dalamud.log](https://github.com/MidoriKami/DailyDuty/files/11183929/dalamud.log)

**Comment by 99bluerabbit** [comment]
The issue has fixed itself now, i do not know if you sent out a fix or the like but it works now. Thanks! :)
