### ISSUE TITLE
[Modification Request] Allow more options for font size and line spacing

### ISSUE THREAD

**Issue by jguluarte** [MidoriKami/DailyDuty#118]
[Context]
I play on a 65" TV, and sit a little ways back

The font size and line spacing have a maximum amount, and this is what it looks like when both values are maxed out. 

![dailyduty](https://user-images.githubusercontent.com/950947/230744784-814f96d7-fc2c-4539-882a-c76fa49c9e62.jpg)

[Request]
Could either the font size and line spacing maximum values be increased? Or allow me to set the font size and line spacing values manually?

**Comment by MidoriKami** [comment]
If you control + click the value in the configuration UI it'll let you put in whatever value you want.

![image](https://user-images.githubusercontent.com/9083275/230745708-7bbef8b6-5682-47d6-9e13-c4567aca42ab.png)
