### ISSUE TITLE
[Usability issue] The daily duty list can be difficult to read 

### ISSUE THREAD

**Issue by jguluarte** [MidoriKami/DailyDuty#119]
[Context]
Depending on what is behind the todo list, it can be difficult to discern from what is behind the list.

![dailyduty](https://user-images.githubusercontent.com/950947/230744784-814f96d7-fc2c-4539-882a-c76fa49c9e62.jpg)

[Request]
Could something change to cause the items in the list to be more distinct from things behind it?

{ideas}
The two thoughts I had were either a more prominent outline on the text, or a settable background?

**Comment by MidoriKami** [comment]
Various upgrades are already planned for the Todo List, so I'm going to close this issue.
I will note however that it seems you're using particularly aggressive shaders which is making it significantly less readable than normal.
