### ISSUE TITLE
Inconsistency in Color Selection Dialouges

### ISSUE THREAD

**Issue by DaCyclops** [MidoriKami/DailyDuty#120]
While setting up the latest version Todo List, I noticed that the color selection widgets for the "Text" and "Text Border" are using the full RGB selector, while the widget for the "Header Outline" is using the predefined list one with no option for customizing.
![image](https://user-images.githubusercontent.com/13886128/230751051-9207404f-888b-4507-b63e-e54eca6ce7f3.png)
![image](https://user-images.githubusercontent.com/13886128/230751061-c560bd09-4342-46c5-a0c7-37d3e19ed55d.png)

**Comment by MidoriKami** [comment]
This is a limitation of the Native UI system. I can set a RGB value for the text color and the outline color, however for "glow" which is what I am using to override the header colors is limited to a UIColor value, which is a predetermined set of values (Those that are shown in the select dialogue).

This is not a bug, it's how it works.
