### ISSUE TITLE
HuntMarksDaily HuntMarksWeekly text is missing

### ISSUE THREAD

**Issue by Eorzean** [MidoriKami/DailyDuty#124]
The task text is missing and only the first task can be enabled.
![clip_1](https://user-images.githubusercontent.com/83107049/230973740-9672205d-fd7b-4daa-9bbd-d0d9bc648cd1.jpg)

**Comment by MidoriKami** [comment]
Does this happen with any other module?
Do you use textools?
What language is your game client?

**Comment by Eorzean** [comment]
HuntMarksDaily/HuntMarksWeekly  Happens only in the module.
textools is not used.
The game client is in Japanese.

**Comment by MidoriKami** [comment]
Please send the following files:
`HuntMarksDaily.config.json`
`HuntMarksDaily.data.json`
`HuntMarksWeekly.config.json`
`HuntMarksWeekly.daya.json`

From: `%appdata%\XIVLauncher\pluginConfigs\DailyDuty\`

**Comment by Eorzean** [comment]
[Reset plugin configuration and reload] gives the same result.
[HuntMarksDaily.config.zip](https://github.com/MidoriKami/DailyDuty/files/11193558/HuntMarksDaily.config.zip)

**Comment by MidoriKami** [comment]
Please attach a copy of your `dalamud.log` with the Hunt Marks Daily window open.

You can find the log in: `%appdata%\XIVLauncher`

**Comment by MidoriKami** [comment]
Additionally, what does the Grand Company (Supply) and Grand Company (Provisioning) configuration pages look like?

**Comment by MidoriKami** [comment]
Fixed in b5785ea
