### ISSUE TITLE
Daily hunts issue

### ISSUE THREAD

**Issue by sajsmith** [MidoriKami/DailyDuty#126]
Daily hunts do not show if you only have HW & Stormblood enabled. soon as you enable  ARR, Shadow bringers or EW it shows up. 

![image](https://user-images.githubusercontent.com/23584299/231804400-a01b20b7-ef70-462b-a18d-d234286c03f5.png)
![image](https://user-images.githubusercontent.com/23584299/231804494-edc18302-7351-4f64-8a84-a185fd45663a.png)
![image](https://user-images.githubusercontent.com/23584299/231804591-063b54d4-72e0-4bae-b569-b3fe4f4c7a11.png)
![image](https://user-images.githubusercontent.com/23584299/231804674-d45d1580-9500-4afd-8eb8-32c5b333614b.png)

if you need any more info let me know

**Comment by MidoriKami** [comment]
Show the data tab

**Comment by sajsmith** [comment]
![image](https://user-images.githubusercontent.com/23584299/231900746-c71b445c-db6c-46db-95ad-78362e5b6776.png)
this one? I cant find another. I just completed the daily hunts I only wanted HW & stormblood tbh

**Comment by sajsmith** [comment]
![image](https://user-images.githubusercontent.com/23584299/232087946-6d2a3a14-40be-4530-a0ea-299469150362.png)
after reset. still showing HW & Stormblood as completed - im not fast enough to do them in 20 minutes lol I do think for some reason they are tagging as weekly instead as they showed Tuesday afternoon

I really need to push you a Koffi at some point, you work hard on this and its just a hobby!

**Comment by MidoriKami** [comment]
Using `/xllog` ingame, set you log level to `debug` and then tomorrow after reset send me a copy of your dalamud.log file

**Comment by sajsmith** [comment]
[dalamud.log](https://github.com/MidoriKami/DailyDuty/files/11239838/dalamud.log)
however, today it seems its working. Im not even going to try guessing.

**Comment by TheMysteron** [comment]
I came to report this, but appears others are having the same issue, daily hunts are not resetting
![DailyDuty_hunt_reset_issue](https://user-images.githubusercontent.com/38109071/232233088-0eea93ca-4f74-455c-be61-e6ad959bcbc1.png)

This screenshot taken ~1 minute after reset

**Comment by TheMysteron** [comment]
Here is my log, after it did not reset again.
[dalamud.log](https://github.com/MidoriKami/DailyDuty/files/11242580/dalamud.log)

**Comment by MidoriKami** [comment]
Can you test to see if this still happens if you are logged out when reset occurs?

**Comment by sajsmith** [comment]
Usually I was online when it ticked over, although there was atleast 1 day I wasnt on at 4pm and it didnt.

It really only righted itself after i put debug on to send you data. Ill keep a eye on it.

**Comment by TheMysteron** [comment]
Was logged out for reset today, and the module is reset correctly.

I noticed in the reset yesterday (and the images above), it resets the modules before the game recognises daily reset (15:59 vs 16:00 based on my local time)

Not sure if it will help at this point, but here is the log file:
[dalamud.log](https://github.com/MidoriKami/DailyDuty/files/11253451/dalamud.log)

**Comment by sajsmith** [comment]
Just completed the hunts (only marked HW & Storm) and not showing completed now.

Also, when I try hide the Treasure map (well snooze till tomorrow) it just... doesnt.
![image](https://user-images.githubusercontent.com/23584299/232614512-2c038b69-11d0-43ca-941b-87ac646c8e87.png)
[dalamud.log](https://github.com/MidoriKami/DailyDuty/files/11255981/dalamud.log)
