### ISSUE TITLE
Grand Company (Squadron) Feature Request

### ISSUE THREAD

**Issue by Dracoman13** [MidoriKami/DailyDuty#128]
A notification to let me know that my squadron is done with their mission would be nice. I'm so paranoid about missing a out on a week's mission, even though I've hardly ever even missed a day, so it would be nice to have DD give me a notification when I log in.

**Comment by MidoriKami** [comment]
Already implemented in 2e41568d950f6ff0cf15ed4f016d3f3cc931fc39 pending next release.
