### ISSUE TITLE
[Feature Request] Add anchor options to duty list

### ISSUE THREAD

**Issue by jguluarte** [MidoriKami/DailyDuty#129]
I like to have my duty list just above my chat window, which is in the lower left of my screen. As such, I prefer to anchor the daily duty list to the bottom left corner of the window and have it grow upwards. 

For me, it's an area of my screen which isn't used as much, so less chance of having it render over the top of other things.

**Comment by MidoriKami** [comment]
Sorta planned.

It's complicated, and I don't have the motivation to do that right now.

So yeah, planned, but not anytime soon.

**Comment by jcastrov** [comment]
I really hope you feel motivated again to re-add the anchors setting once more. I loved that feature in the previous version with the color labels; It looked so natural, like it was not a plugin at all.

I know that adding the setting in the non-native UI element can be hard. Maybe you can consider the possibility of adding both versions if it's complicated to add the anchor setting to the new one.

Last but not least, thank you so much for this useful plugin.
