### ISSUE TITLE
Keep pop-out window open at launch?

### ISSUE THREAD

**Issue by spiral6** [MidoriKami/DailyDuty#13]
Pretty much what the title says. When I log in to the game, the Daily Duty pop-out window has to be turned on from the settings.

**Comment by MidoriKami** [comment]
What version

**Comment by xPumaa** [comment]
I had the same problem. Works now with version 1.0.1.0

**Comment by spiral6** [comment]
I'm on version 1.0.1.0 and it's still happening.
