### ISSUE TITLE
Todo List - Fill from bottom

### ISSUE THREAD

**Issue by Ahumaya** [MidoriKami/DailyDuty#133]
Would it be possible to add a configuration option to have the Todo list fill from the bottom of the window?

I prefer to align my list with the bottom left corner of the screen, and to have the info move upwards as new tasks are presented, and for the info to move downwards as tasks are completed. The previous iteration did allow this as an option, however the newly updated (and noticeably more customizable) iteration does not currently have this option as far as I can see.
![image](https://user-images.githubusercontent.com/82483575/232792871-480d1c08-a068-4eb2-b4c4-1706d7929627.png)

**Comment by MidoriKami** [comment]
Duplicate #129
