### ISSUE TITLE
ToDo Display Error

### ISSUE THREAD

**Issue by asmoranomar** [MidoriKami/DailyDuty#135]
~~After completing all the tracked tasks~~, the ToDo window experiences a display error. (Edit: Unsure if completing tasks is the issue, I can add more tasks and the issue doesn't fix itself)
The content is empty, but the ToDo list expands quite a bit vertically.  If the ToDo has Background Opacity set, the ToDo list obscures the entire length of the screen.

https://i.imgur.com/FNfzkMm.png

This does not occur when you set the preview mode.
This does not occur when you disable the ToDo Display (for obvious reasons).
This does not occur when you disable the plugin (...of course).
Enabling the plugin, the ToDo Display and/or disabling the preview makes the problem reappear.

**Comment by MidoriKami** [comment]
Duplicate #130
