### ISSUE TITLE
Issue with treasure map tracking

### ISSUE THREAD

**Issue by HeroGarr** [MidoriKami/DailyDuty#139]
Hello.

I've recently stumbled upon an issue with treasure map tracking.

When you actually gather the map in game, the task is gone from reminders, and everything seems fine, module data is updated. That is, until you restart the game, then the module data is reset to last gather on 16th of April, so the task reappears, even though timer for the next map allowance is still ticking down.

![изображение](https://user-images.githubusercontent.com/10124529/233148111-e419e6a4-be8c-402c-a4cf-ca454604df00.png)

Is there an issue on my end, and can I somehow reset this data? Seems like that 16th gathering time is stuck in a cache or file somewhere, but I'm not sure where or how it can be released.

**Comment by MidoriKami** [comment]
Fixed in d4c629bb027c43b96c444b928dd24684c00e2cc8, pending release.
