### ISSUE TITLE
Issue with Todo display when all tracked tasks completed

### ISSUE THREAD

**Issue by TarmonTarupon** [MidoriKami/DailyDuty#144]
There's a big red "No DailyDuty Modules Enabled" message that appears once all tracked tasks are completed for the day/week.
https://i.imgur.com/yWZ603D.png
It says no modules enabled but I have quite a few modules enabled, they are just completed. Previously, the area where the Todo display is would just be blank once I was finished with the tasks, but now the big red letters are there until I either turn off the Todo display, or add another module that I do not wish to track.

**Comment by MidoriKami** [comment]
Ah,.oops, I forgot to make a distinction between nothing enabled and everything done. 

Thanks for the report.

**Comment by MidoriKami** [comment]
Fixed in 5a0af6d045a0878c2d92d148cf414c562b3ac83a
