### ISSUE TITLE
More detailed view for multistage duties

### ISSUE THREAD

**Issue by RainerZufahl** [MidoriKami/DailyDuty#15]
The popout window could feature more information when displaying duties with multiple stages, like Duty Roulette or Hunt Marks. I could imagine something like displaying a small window on hovering the title, or maybe having it as an expandable section, which then shows the separated sub-duties (each selected roulette type, each hunt mark and so on).

Ideally, this should work in conjunction with #14, so that completed subduties will also appear in the pop-up, making for a quick look whats still to be done.

**Comment by MidoriKami** [comment]
May revisit this in the future. For now need to finish all modules first.
