### ISSUE TITLE
[Bug] Todo not visible

### ISSUE THREAD

**Issue by xPumaa** [MidoriKami/DailyDuty#155]
I turn off the Todo window for the raid with "/dd todo hide". When I want to show the window again after the raid with "/dd todo show", the Todo window is not shown anymore.

When you unhide it, no error is displayed in "/xllogs" either

This happens only after a longer time. I tried to reproduce the problem with hide, duty and show, but then it works normally.

**Comment by MidoriKami** [comment]
Send config file

**Comment by xPumaa** [comment]
[DailyDuty.zip](https://github.com/MidoriKami/DailyDuty/files/11790493/DailyDuty.zip)

**Comment by MidoriKami** [comment]
I'll need a video of this bug happening to have enough information to act on it. As it is now I have nothing to work with.

I'm going to close this issue for now, re-open it if you are able to provide video of the bug occurring again.

**Comment by xPumaa** [comment]
I got it reproduced. It is similar to #141 only without crashes.
