### ISSUE TITLE
Red Square Never Goes Away

### ISSUE THREAD

**Issue by Astral-Crescent** [MidoriKami/DailyDuty#157]
I used to love this mod, was the only reason I was able to play the game due to my mental health, but ever since you started changing things with how it looks and works I have both stopped using the mod and stopped playing the game. 

At the current state there is a permanent red border around the task list that NEVER goes away-- even if I DISABLE the mod. I have to completely Uninstall it to make it go away. I can not stand the color red it makes me miserable from how distracting it is and ruins my game-play experience, but I cannot play this game without the functionality of Daily Duty. 

One; it needs the ability to Remove and Two; it needs the ability to recolor.

**Comment by MidoriKami** [comment]
Turn this option off. The border isn't a feature, its to indicate that there's an invisible window there that you can click and drag. It is absolutely not recommended to keep that draggable window enabled.

If disabling it doesn't remove it then you probably have multiple versions of DailyDuty installed at the same time somehow.

![image](https://github.com/MidoriKami/DailyDuty/assets/9083275/126eba68-3045-479e-9c71-640ba1d88f2c)
