### ISSUE TITLE
Preview mode causing crashes

### ISSUE THREAD

**Issue by ChaseS-Dev** [MidoriKami/DailyDuty#158]
Initially, it crashed when trying to disable the preview mode then crashed on login until disabling the plugin.

**Comment by ChaseS-Dev** [comment]
[dalamud_appcrash_20230825_080955_902_26528.log](https://github.com/MidoriKami/DailyDuty/files/12439482/dalamud_appcrash_20230825_080955_902_26528.log)

**Comment by MidoriKami** [comment]
Likely corrupted config file, try resetting your configs.

**Comment by ChaseS-Dev** [comment]
Sure enough after deleting the config files everything was working as intended. I guess uninstalling the plug-in and reinstalling isn’t enough to reset them.

**Comment by MidoriKami** [comment]
>  I guess uninstalling the plug-in and reinstalling isn’t enough to reset them.

This is correct, uninstalling a plugin does not reset the configs for the plugin, you can right click the plugin in the installer to "Reset configuration data and reload" that will clear all the configs.
