### ISSUE TITLE
Plugin failed to load

### ISSUE THREAD

**Issue by NeikoSeiteki** [MidoriKami/DailyDuty#161]
Hi,
the plugin failed to load with Dalamud.
Uninstall and reinstall it doesn't work... (even with reloading the game)
Do you know what can be the issue ?

Thanks !

<img width="401" alt="Image1" src="https://github.com/MidoriKami/DailyDuty/assets/103772557/3eaa4c3e-d14b-4636-9c91-0d46f2dbd3a2">

**Comment by MidoriKami** [comment]
![image](https://github.com/MidoriKami/DailyDuty/assets/9083275/3dcffecb-19ab-41a9-b340-ffdb97c4831a)
Your configuration files are corrupted, delete the DailyDuty folder in this directory.
