### ISSUE TITLE
[Feature Request] Tracking weekly aglaia/euphrosyne/thaleia coins

### ISSUE THREAD

**Issue by nonamethanks** [MidoriKami/DailyDuty#163]
You can only get one aglaia/euphrosyne/thaleia coin a week from the respective alliance raid, and they're used to [upgrade credendum ilvl 650 items to ilvl 660](https://ffxiv.consolegameswiki.com/wiki/Divine_Shine), so this definitely counts as a weekly task.

Not sure how hard/annoying this would be to track from a development standpoint.

**Comment by MidoriKami** [comment]
Already tracked in the alliance raid module.
