### ISSUE TITLE
change wonderous tails task name when book unclaimed

### ISSUE THREAD

**Issue by jacob-keller** [MidoriKami/DailyDuty#164]
Right now the daily tasks list shows "wonderous tails" as a task, which just tells you that you haven't yet 100% completed the book. Since I tend to take time over the week to complete, it would be very useful if it had a diff name "wonderous tails (book unclaimed)" or similar in the event where I haven't yet picked up the book for the week. This would help distinguish and make it easier to remember to pick up a new book on reset day (or after, if I happen to have forgotten on reset day)

**Comment by MidoriKami** [comment]
I don't really see the value in this.

If you are using the on-screen todo list and have the clickable links enabled, clicking on "Wondrous Tails" will teleport you directly to Idylshire if a new book is needed, or it will simply open the task book.
