### ISSUE TITLE
New feature: add own tasks

### ISSUE THREAD

**Issue by pitripan** [MidoriKami/DailyDuty#167]
Hi,
I have looked over the closed issues so far and didn't find something like this, so I thought I'd suggest this one. Do you think it would be possible to add a new feature for players to add own (configurable) tasks on their own? 

**Example:** 
I want to add a new weekly task "create new glamour plate". So I go into plugin config, add a new task, set it's frequency to "weekly" and enter a title. Then it's shown in the list until I click (or maybe shift/strg/alt-click) in the list (or check a checkbox or something). Then it's completed for the configured period and gets reset on weekly reset.

I think this would be a great feature and would (maybe) prevent those "add island sanctuary" requests as each of them could add it on their own.
If you don't want to add something like that I would totally understand it but I thought I suggest this anyways. 

Thanks for the plugin so far and keep on the great work!

Best regards
Pitri

**Comment by MidoriKami** [comment]
I had originally considered adding features like that to DailyDuty, however I determined it would be much better as a standalone plugin instead and not a good fit for the DailyDuty codebase.

**Comment by pitripan** [comment]
I'm quite new to using plugins. Do you know a plugin where I could do something like that or are you planning on coding one? ;)

**Comment by MidoriKami** [comment]
I am not currently planning on making any more plugins.
