### ISSUE TITLE
Mark tasks as done manually when using multiple devices?

### ISSUE THREAD

**Issue by Kvoo** [MidoriKami/DailyDuty#168]
I use my Steam Deck as well as my PC for FFXIV, got your plugin on both. `

The only issue is that switching devices obviously doesn't sync the status between them, which means I have to go to the location for each task and interact with the corresponding NPC to get the task to show as done.

Is there a way to manually tell the plugin that xyz tasks are already done, without going to the NPCs?

**Comment by MidoriKami** [comment]
Yes. Hit the snooze button in the data data for the task
