### ISSUE TITLE
[BUG&Feature Request] Daily Duty partially in german despite game being in english, same as dalamud language. Possible to rename headers?

### ISSUE THREAD

**Issue by Shiichibukai** [MidoriKami/DailyDuty#171]
![image2](https://github.com/MidoriKami/DailyDuty/assets/96307333/f1122791-4a96-4158-be52-9acf435363fa)
![image](https://github.com/MidoriKami/DailyDuty/assets/96307333/de17c19e-d23a-4dc0-87b9-62b416061f23)
![image3](https://github.com/MidoriKami/DailyDuty/assets/96307333/aeacb77b-7491-4d74-afcc-034865f5f70e)

Dalamud and Game language is in english. Swapping back and forth did not work
Turning off plugin and back on didnt work
ToDo list on and off didnt work aswell.

Also feature request sneakily - or if it exists and im just blind > can we name the headers again? Would like to add some lil symbols to make em fancy again.

**Comment by Kery0x** [comment]
Hello. Same problem here except my DailyDuty is in french for most of its components
My game is in english and dalamud as well.

![image](https://github.com/user-attachments/assets/65d1211f-0958-4437-8bfa-2061e6412613)

**Comment by MidoriKami** [comment]
Seems to be resolved, closing.
