### ISSUE TITLE
[Feature Request] Hide Header when all tasks in category complete.

### ISSUE THREAD

**Issue by MinoWizard** [MidoriKami/DailyDuty#172]
Previous versions of DailyDuty would hide the header text when all tasks within their category were completed. In the current version of DailyDuty, headers remain even if all tasks in that category are complete.

For example's sake, the below image shows the Special Tasks header remaining even though there are no available tasks underneath it.

![dd](https://github.com/MidoriKami/DailyDuty/assets/22230148/94128791-7d9d-4f40-be98-6f2737de1dad)

I'd like a checkbox to re-implement this feature of hiding categories when all tasks are complete.

**Comment by Terin** [comment]
Seconding this, along with requesting an option to hide the entire dialog when all tasks are complete. Can replicate that with an entirely transparent background and no headers, but we should be able to use both and have them vanish when cleared.
