### ISSUE TITLE
[Bug] Right hand Alignment breaks with headers depending on Task Length

### ISSUE THREAD

**Issue by MinoWizard** [MidoriKami/DailyDuty#174]
When using the Category Style options Bottom Right, or Top Right, the headers will sometimes improperly align depending on the length of tasks in its category. Particularly long tasks can shift the header title to a left alignment.

In the following image example, the "Weekly Tasks" header is aligned to the left to fit with the Grand Company (Squadron) task, when it is intended to be aligned to the right of the screen.

![dd align](https://github.com/MidoriKami/DailyDuty/assets/22230148/61b547f7-cb8f-43f0-b85c-50e54d37210b)

**Comment by eaganlai** [comment]
Adding to this.
The same thing would happen to Daily Tasks if you have the Grand Company (Provision) or (Supply) enabled.
![image](https://github.com/user-attachments/assets/355c59a1-037e-4977-9006-4c00aa23ded2)
![image](https://github.com/user-attachments/assets/42d3c11a-7361-48cd-ada0-8e32ebc6c232)
