### ISSUE TITLE
[Feature Request] Header spacing option

### ISSUE THREAD

**Issue by rechington** [MidoriKami/DailyDuty#175]
As with the other parts, would be nice to have a header spacing option to accurately mimic the vanilla quest log appearance. Currently this is not possible, as the module spacing affects the distance between modules themselves, and not just the header, and the vanilla quest log has different spacing for those.

**Comment by MidoriKami** [comment]
I don't really care about being able to "mimic vanilla"

Can you instead describe your actual request without comparing it to vanilla?
