### ISSUE TITLE
Add ticket function did not work correctly

### ISSUE THREAD

**Issue by xPumaa** [MidoriKami/DailyDuty#18]
When 3 tickets are available, the add ticket button is not working.
I added a ticket manually via the configuration file and then it worked.

It is also possible to go below zero with the button.

My guess you have to change the if statement
```c#
if (GetAvailableTickets() < 3)
```
to
```c#
var availableTickets = GetAvailableTickets();
if (availableTickets  <= 3 && availableTickets > 0)
```

**Comment by MidoriKami** [comment]
Already fixed before you posted that in 1fda2e38aa7b00428d60b716415dd0f9c99edc0b
