### ISSUE TITLE
[Feature Request] Re-implement(?) preview/test mode for UI box

### ISSUE THREAD

**Issue by shinji257** [MidoriKami/DailyDuty#180]
There used to be an option to preview the daily duty box with all the options enabled and lines visible so you could place it appropriately on the screen.  Is this option still present and hiding or will it be reimplmented in the future?  I can't seem to find it but I may be missing it when looking through the settings in the current testing release.

**Comment by MidoriKami** [comment]
Enable show background for the to-do list and it'll show you the bounds. The area hard clips so if anything tries to expand larger it'll get cut off.

**Comment by shinji257** [comment]
There was an option to show all text for all options as if you had to do them still so you could preview the layout without having to affect your current configuration.  That's what I was hoping to get.  It existed in previous versions but if you do not plan to reimplement then I'll just sort it out.
