### ISSUE TITLE
[Question]: Masked Carnivale doesn't update to completed upon viewing timers

### ISSUE THREAD

**Issue by cecilia-sanare** [MidoriKami/DailyDuty#182]
### Description

This *may* actually be a feature request I honestly don't know if it did this prior or not.
Prior to Dalamud being updated for 7.01 I completed Masked Carnivale. 
However opening the timers window (which is the usual fix for the others) doesn't seem to get it to realize that it has been completed.
Talking to the Celestium Attendant also doesn't seem to cause DailyDuty to realize that its been completed either.

### Screenshots

![image](https://github.com/user-attachments/assets/ca594b5b-91a7-42af-a58d-7054539e1b43)

**Comment by MidoriKami** [comment]
Opening timers window is not something I have it programmed to check, opening timers causes the game itself to initialize some systems.

The resync trigger for Masked Carnivale is viewing the Masked Carnivale duty selection window
