### ISSUE TITLE
Disabled due to incompatibilities

### ISSUE THREAD

**Issue by EdwardShipp** [MidoriKami/DailyDuty#183]
Dalamud still lists Daily Duty as outdated, but has a slightly different line as to most other plug-ins.
"This plugin was automatically disabled due to incompatibilities and is not available. Please wait for it to be updated by its author."

**Comment by MidoriKami** [comment]
Not a DailyDuty issue seek help in the XIVLauncher discord

**Comment by Erumite** [comment]
If anyone else is still wondering, I'll save you having to get into the Discord.  There was a post on the 9th that the plugin was temporarily blocked for causing repeatable crashes.  Lots of people have asked about it in the interim, but not much in the way of responses aside from that it's still being tested and can still sometimes crash you.
