### ISSUE TITLE
Plugin causes crash when logging in

### ISSUE THREAD

**Issue by GregariousJamie** [MidoriKami/DailyDuty#184]
Hey, you're probably already aware of this, or maybe its just happening to me, no clue, heres my log anyway

[dalamud_appcrash_20240718_105458_977_22592.log](https://github.com/user-attachments/files/16276281/dalamud_appcrash_20240718_105458_977_22592.log)

Hopefully you're able to get to it soonish, this is one of my fav plugins

**Comment by MidoriKami** [comment]
See XIVLauncher discords known issues post.

**Comment by shinji257** [comment]
I'm just going to drop this just in case anything comes up in the future.  Slightly different crash but I think it is the same cause.  I had to disable DailyDuty for now as it causes me to crash when I login.  If I disable it until I login I crash as soon as it is enabled right after it prints the daily duty related text in chat.

[crash-20240717211258.tspack.zip](https://github.com/user-attachments/files/16276754/crash-20240717211258.tspack.zip)
