### ISSUE TITLE
"Special Tasks" and "Weekly Tasks" headers remain in to-do list, even if all sub-entries for the day have been completed, unlike other sections.

### ISSUE THREAD

**Issue by A4L3B75359** [MidoriKami/DailyDuty#189]
![image](https://github.com/user-attachments/assets/14fedfa7-154a-4472-9fab-17691088943c)
![image](https://github.com/user-attachments/assets/eccdd6d1-c520-4286-9ecc-902086adbf70)

Enabled modules: Leves, fashion report, grand company (squadron), jumbo cactpot, mini cactpot.

For the time being ive just been manually turning off headers after completion.

**Comment by MidoriKami** [comment]
Send all config files for that character

**Comment by A4L3B75359** [comment]
Sorry for the wait.
[TodoList.config.json](https://github.com/user-attachments/files/16355121/TodoList.config.json)
[TreasureMap.config.json](https://github.com/user-attachments/files/16355122/TreasureMap.config.json)
[TreasureMap.data.json](https://github.com/user-attachments/files/16355123/TreasureMap.data.json)
[TribalQuests.config.json](https://github.com/user-attachments/files/16355124/TribalQuests.config.json)
[TribalQuests.data.json](https://github.com/user-attachments/files/16355125/TribalQuests.data.json)
[WondrousTails.config.json](https://github.com/user-attachments/files/16355126/WondrousTails.config.json)
[WondrousTails.data.json](https://github.com/user-attachments/files/16355127/WondrousTails.data.json)
[ChallengeLog.config.json](https://github.com/user-attachments/files/16355128/ChallengeLog.config.json)
[ChallengeLog.data.json](https://github.com/user-attachments/files/16355129/ChallengeLog.data.json)
[CustomDelivery.config.json](https://github.com/user-attachments/files/16355130/CustomDelivery.config.json)
[CustomDelivery.data.json](https://github.com/user-attachments/files/16355131/CustomDelivery.data.json)
[DomanEnclave.config.json](https://github.com/user-attachments/files/16355132/DomanEnclave.config.json)
[DomanEnclave.data.json](https://github.com/user-attachments/files/16355133/DomanEnclave.data.json)
[DutyRoulette.config.json](https://github.com/user-attachments/files/16355134/DutyRoulette.config.json)
[DutyRoulette.data.json](https://github.com/user-attachments/files/16355135/DutyRoulette.data.json)
[FashionReport.config.json](https://github.com/user-attachments/files/16355136/FashionReport.config.json)
[FashionReport.data.json](https://github.com/user-attachments/files/16355137/FashionReport.data.json)
[FauxHollows.config.json](https://github.com/user-attachments/files/16355138/FauxHollows.config.json)
[FauxHollows.data.json](https://github.com/user-attachments/files/16355139/FauxHollows.data.json)
[GrandCompanyProvision.config.json](https://github.com/user-attachments/files/16355140/GrandCompanyProvision.config.json)
[GrandCompanyProvision.data.json](https://github.com/user-attachments/files/16355141/GrandCompanyProvision.data.json)
[GrandCompanySquadron.config.json](https://github.com/user-attachments/files/16355142/GrandCompanySquadron.config.json)
[GrandCompanySquadron.data.json](https://github.com/user-attachments/files/16355143/GrandCompanySquadron.data.json)
[GrandCompanySupply.config.json](https://github.com/user-attachments/files/16355144/GrandCompanySupply.config.json)
[GrandCompanySupply.data.json](https://github.com/user-attachments/files/16355145/GrandCompanySupply.data.json)
[HuntMarksDaily.config.json](https://github.com/user-attachments/files/16355146/HuntMarksDaily.config.json)
[HuntMarksDaily.data.json](https://github.com/user-attachments/files/16355147/HuntMarksDaily.data.json)
[HuntMarksWeekly.config.json](https://github.com/user-attachments/files/16355148/HuntMarksWeekly.config.json)
[HuntMarksWeekly.data.json](https://github.com/user-attachments/files/16355149/HuntMarksWeekly.data.json)
[JumboCactpot.config.json](https://github.com/user-attachments/files/16355150/JumboCactpot.config.json)
[JumboCactpot.data.json](https://github.com/user-attachments/files/16355151/JumboCactpot.data.json)
[Levequest.config.json](https://github.com/user-attachments/files/16355152/Levequest.config.json)
[Levequest.data.json](https://github.com/user-attachments/files/16355153/Levequest.data.json)
[MaskedCarnivale.config.json](https://github.com/user-attachments/files/16355155/MaskedCarnivale.config.json)
[MaskedCarnivale.data.json](https://github.com/user-attachments/files/16355156/MaskedCarnivale.data.json)
[MiniCactpot.config.json](https://github.com/user-attachments/files/16355157/MiniCactpot.config.json)
[MiniCactpot.data.json](https://github.com/user-attachments/files/16355159/MiniCactpot.data.json)
[RaidsAlliance.config.json](https://github.com/user-attachments/files/16355160/RaidsAlliance.config.json)
[RaidsAlliance.data.json](https://github.com/user-attachments/files/16355162/RaidsAlliance.data.json)
[RaidsNormal.config.json](https://github.com/user-attachments/files/16355163/RaidsNormal.config.json)
[RaidsNormal.data.json](https://github.com/user-attachments/files/16355164/RaidsNormal.data.json)
[System.config.json](https://github.com/user-attachments/files/16355165/System.config.json)
[Timers.config.json](https://github.com/user-attachments/files/16355166/Timers.config.json)
