### ISSUE TITLE
Task status hints continue to show in the Duty Finder even when coloring and/or module is disabled

### ISSUE THREAD

**Issue by shinji257** [MidoriKami/DailyDuty#190]
See image
![image](https://github.com/user-attachments/assets/a0960f97-35bc-43b7-9d9d-5a5c8a918377)

Duty finder coloring is currently disabled as per lack of coloring is missing from actual entries but hints remain below the list.

**Comment by MidoriKami** [comment]
Already fixed in 8d4ba400f4acb7fa606c3e9a9aa5665788dbed87

Please update the plugin.
