### ISSUE TITLE
Dawntrail normal raids (The Arcadion) not tracked?

### ISSUE THREAD

**Issue by pitripan** [MidoriKami/DailyDuty#195]
Hey there,
right now I don't see the possibility to track The Arcadion normal raid within Daily Duty. Do I have to config something myself or are they currently not supported?
Within Normal Raids I only have a tracker for Anabaseios 12th circle.

Best regards and thank you for coding!

**Comment by MidoriKami** [comment]
Unable to reproduce, module was fixed in a previous update.

**Comment by MidoriKami** [comment]
Seems others are having an issue as well.

Deleting the data file for the module should manually fix it.

**Comment by pitripan** [comment]
Can you tell me where to find the data file? Then I would give this a try.

**Comment by pitripan** [comment]
Just confirming it's working now. Thank you!
