### ISSUE TITLE
smaller timer text

### ISSUE THREAD

**Issue by Megagalatkikarea2** [MidoriKami/DailyDuty#196]
any chance we can get an option to change the size of the timer text?
![image](https://github.com/user-attachments/assets/c642e90a-d2b3-42e1-a18c-c3bf29d9fcfe)

**Comment by Megagalatkikarea2** [comment]
Also hunt bills don't reset correctly

**Comment by MidoriKami** [comment]
Please don't post multiple distinctly different issues in the same post.
