### ISSUE TITLE
ToDo list disappears on Island Sanctuary

### ISSUE THREAD

**Issue by EmpressAnarchy** [MidoriKami/DailyDuty#198]
When visiting my Island Sanctuary, the list disappears and doesn't come back when I teleport away.

Testing:
The list is available in free mode, but disappears when I switch away from free mode (i.e. gather, sow, etc.)
The plugin is still active as I can pull up the config options with /dd.
I tried to get it to reappear by disabling and re-enabling in Dalamud, but this did not work.

Ways to resolve:
Unchecking 'Hide During Quest Events' causes the list to reappear, but will disappear again when re-checked. (Even when doing this when out of the Island Sanctuary instance.)
Logging out and back in will cause the list to reappear.
Visiting the Island Sanctuary and switching back to free mode will resolve the issue - when I re-visited, I was still in gather mode, so it looks like FFXIV is remembering something within the session.

Totally understandable if you don't want to fix this, but wanted to report in case anyone else notices the strange behavior.

**Comment by MidoriKami** [comment]
Working as expected. Square defines gathering operations in the island sanctuary as a quest event.
