### ISSUE TITLE
Add resize support

### ISSUE THREAD

**Issue by Iaotle** [MidoriKami/DailyDuty#2]
Currently the size of the box is big and very intrusive. Let us resize it.

**Comment by MidoriKami** [comment]
The UI elements would not move around properly, so unless the current size is an actual usability problem I intend to leave it as is.

**Comment by MidoriKami** [comment]
Additionally, the plugin is meant to be configured to pester you in chat, other than the "ToDo List" there's no reason to keep the UI open for long periods of time.

I may make the ToDo List a popout window that users can anchor on their screen but that's a thought for later~
