### ISSUE TITLE
Weird background behavior with ToDo List

### ISSUE THREAD

**Issue by Delaene** [MidoriKami/DailyDuty#200]
Selecting "top right" anchor in the general configuration tab makes the list and the background disalign
![image](https://github.com/user-attachments/assets/22750173-2490-4368-8c87-1dbe4e683d49)

Selecting "top left" causes no issues
![image](https://github.com/user-attachments/assets/e3df871c-4a79-41a5-8ee4-0012bbc7a460)

**Comment by MidoriKami** [comment]
Fixed in 342d45ed4e7ab13df53e27c835e3eea10f497d85
