### ISSUE TITLE
Update wipes configuration

### ISSUE THREAD

**Issue by femxiii** [MidoriKami/DailyDuty#204]
The last couple of updates have reset the modules I've had enabled and their settings (i.e. notifications).

It doesn't seem to reset the reset of the config (for example, position and layout of the frame)

**Comment by MidoriKami** [comment]
I'll not this issue for future reference if other's continue to have this issue they can make it known here.

**Comment by cjtylr** [comment]
Same issue here. Lost all settings after today's and the previous update.

**Comment by zsdonny** [comment]
my settings got wiped again yamero

**Comment by MidoriKami** [comment]
> my settings got wiped again yamero

Unrelated. This update intentionally reset timers config and Todo config and did not reset any other configs.
