### ISSUE TITLE
Treasure Map detection/suppression not working

### ISSUE THREAD

**Issue by SnoFox** [MidoriKami/DailyDuty#205]
I've been having issues with the Treasure Map detection for a while.

1. Treasure Maps aren't being detected as completed. I've been Spearfishing maps in DT Z4 for most of the expansion.
2. Attempting to suppress the check by shift + control clicking the Snooze button just ignores me. Other timers can be successfully suppressed, however.

I originally did not report this as I thought it was a Linux-specific issue, but I've been having the suppression on both Windows and Linux.

![image](https://github.com/user-attachments/assets/42edea9b-39dd-4554-957f-56c1a4b22770)

**Comment by PhilShwartz** [comment]
having the same issue as well, seems like it affects spearfished maps specifically

**Comment by MidoriKami** [comment]
Do you happen to have a dalamud.log file to share?

**Comment by SnoFox** [comment]
Tomorrow, I'll load up the game without 3rd party repos and grab a map to validate it's not something crazy with Penumbra and attach it.

**Comment by SnoFox** [comment]
I've attached the dalamud.log file as requested. Game was launched without third party plugins.
[dalamud - dd tm.log](https://github.com/user-attachments/files/16683966/dalamud.-.dd.tm.log)

**Comment by MidoriKami** [comment]
Ah your log needs to be in debug mode `/xllog`, and set the top left most option to `Debug+`

**Comment by SnoFox** [comment]
Here you are! I TP'd to my spearfishing spot, changed to fisher, grabbed my map, tried to snooze the task 3 times, TP'd to a sanctuary and logged out.

[dalamud - dd tm debug.txt](https://github.com/user-attachments/files/16700997/dalamud.-.dd.tm.debug.txt)

**Comment by MidoriKami** [comment]
fixed in d4fd5f687fb164c7574124692e2a3368a3cb058d
