### ISSUE TITLE
Unable to load: Requiring WQHD/4k resolution

### ISSUE THREAD

**Issue by MidoriKami** [MidoriKami/DailyDuty#206]
Requires this setting in the System Configuration option to be set.

The plugin will not load if this setting is not set to the shown value. This is intentional behavior.

After changing to this setting a game restart is required.

![image](https://github.com/user-attachments/assets/b10dab54-b1c7-4998-977f-e54b530eb749)

**Comment by gilles007-** [comment]
this setting has a cost in CPU for me
is it possible to make it optional ?

**Comment by MidoriKami** [comment]
That setting has a GPU VRAM cost, not a CPU cost.

**Comment by gilles007-** [comment]
my GPU is 10 years old too
you know what : my PC has freezed 1h after enabling this option
how could this option be mandatory to display 1 line of text ?
if you don't want to make it optional, how could i grab an old version and install it ?
