### ISSUE TITLE
Category empty when hiding module from Todo Display

### ISSUE THREAD

**Issue by Gakai** [MidoriKami/DailyDuty#207]
When I enable Duty Roulette, but uncheck the "Enable Todo Display" option, the heading "Daily Tasks" still shows even though I completed every visible entry in that category.
This behavior only happens if at least one checked Duty is not completed.

## My settings
![image](https://github.com/user-attachments/assets/0540f8c8-a965-4f36-ba3c-f4c814b452ba)
![image](https://github.com/user-attachments/assets/d6f31613-592e-47e6-88ac-5efe404a493d)

## This is my complete Todo List
(some tasks are already done, but Duty Roulette definitely not 😁)
![image](https://github.com/user-attachments/assets/ed76c4ad-028a-4ffe-9dbd-9132a3aac471)

**Comment by MidoriKami** [comment]
Sorry going to close this as I am actively working on a rework of that system.

**Comment by MidoriKami** [comment]
If this issue is present with the new system (Version 5.1.0.0+), open a new issue instead of reopening this issue.
