### ISSUE TITLE
Treasure map not updating

### ISSUE THREAD

**Issue by nicuity** [MidoriKami/DailyDuty#208]
![map](https://github.com/user-attachments/assets/b71655d0-1f76-4c5c-a124-56d53c91cad5)
Time as of SS is 8/26 @ 10:46 am so well ahead of 18 hour respawn. Treasure map allowance in timer tab says it's available.

**Comment by MidoriKami** [comment]
Give it a day then if it still is having issues repo l re open.

**Comment by MidoriKami** [comment]
Superseded by version 5.1.0.0
