### ISSUE TITLE
UI task list missing functionality

### ISSUE THREAD

**Issue by jgh713** [MidoriKami/DailyDuty#209]
As of the latest styling update, there's two bits of functionality the UI task menu seems to have lost.

A) Clickable teleport links no longer function on the menu, only in chat
and
B) Hovering over certain entries (e.g. Challenge Log) no longer shows relevant info (e.g. which Challenge Log entries are unfinished)

The first one is a minor annoyance, but the second one is a pretty major loss of QoL, especially since that hover-info functionality doesn't exist on the chat links, it only existed on the UI menu.

I'm not sure if this was an intentional change or not, but these two features are like 90% of how I interact with the DailyDuty plugin, so it's a pretty substantial downgrade in QoL.

**Comment by MidoriKami** [comment]
Not intended I'll take a look when I have time

**Comment by DanteLuck** [comment]
What i noticed is that the UI settings were reset with this latest update as well, its a minor issue as i did not put more than 5-10 minutes into placing it properly and setting it up.

**Comment by MidoriKami** [comment]
> What i noticed is that the UI settings were reset with this latest update as well, its a minor issue as i did not put more than 5-10 minutes into placing it properly and setting it up.

This reset was intentional, it was the only way to provide extra functionality.
