### ISSUE TITLE
Warning Message When Queuing Same Daily Roulette Multiple Times

### ISSUE THREAD

**Issue by SelfAfflicted** [MidoriKami/DailyDuty#21]
Would you consider adding an option for a warning message, maybe with the error notification sound, stating 'you've already done this roulette today' upon clicking join? Most times when I use Duty Finder and I've a previous roulette ticked from last use, I tend to click the next one and hit join assuming it's what I want, based on the right pane changing, when in reality I just joined for the same roulette.

**Comment by MidoriKami** [comment]
Alternate approach currently being researched is automatically unselecting the last duty when clicking the roulette action link

**Comment by MidoriKami** [comment]
The new Duty Roulette overlay should sufficiently solve this problem also when paired with the clickable action-links for Duty Roulette selecting the "next" incomplete duty.

I believe this solution to be more intuitive and easier to use than a warning.

![image](https://user-images.githubusercontent.com/9083275/155439978-bb6f7185-cbd4-4c2c-9f5f-a6ecab2962e0.png)
