### ISSUE TITLE
"Complete When Tomecapped" > "Only Show Expert Complete" still marks whole Duty Roulette Module as complete

### ISSUE THREAD

**Issue by ShermTank7272** [MidoriKami/DailyDuty#214]
The "Only Show Expert Complete" toggle still marks the whole Duty Roulette module as complete. Toggling the Expert option on/off will mark the Expert roulette itself as complete/incomplete in the "Module Data" view, but the module as a whole will still be marked as complete when tomecapped. Only when the "Complete When Tomecapped" toggle is removed will the module as a whole be marked as incomplete. See attached screenshots.

Expected behavior _(please correct me if I am wrong)_: When the "Complete When Tomecapped" and "Only Show Expert Complete" toggle are both enabled and I am tomecapped, the Duty Roulette module will be "incomplete" until normal completion conditions are met but the Expert roulette will be "complete".

![image](https://github.com/user-attachments/assets/b8d946d1-06ab-432e-90cb-29a59089d22d)
![image](https://github.com/user-attachments/assets/15d7864d-0bb9-4f98-9b40-11bcba19aaab)
![image](https://github.com/user-attachments/assets/70474b67-022f-4ca6-a6ef-814c3e5eb1ec)

**NOTE:** I noticed that the "expected behavior" above _did_ occur when I toggled "Only Show Expert Complete" on and _then_ toggled "Complete When Tomecapped" off, despite the 'Expert' toggle disappearing when the 'Tomecapped' toggle is turned off. See below:

![image](https://github.com/user-attachments/assets/a690aaa4-97d1-414a-b61b-ee6e713f1f71)

**Comment by MidoriKami** [comment]
After further review, this is a wording issue.

The intent of the provided option was to not show `Expert` as `Incomplete` in the Duty Finder Overlay, when you are at your weekly tome limit.

Suggestions on how to improve the wording would be appreciated.

**Comment by ShermTank7272** [comment]
> The intent of the provided option was to not show Expert as Incomplete in the Duty Finder Overlay, when you are at your weekly tome limit.

That part of it is, in my opinion, working as intended and clearly worded. Toggling "Only Show Expert Complete" on and off will show the Expert roulette as 'complete' or 'incomplete' respectively.

The concern that I have is in regards to the completion status of **the Duty Roulette module as a whole**. What I was thinking would happen _(and again, please correct me if I am wrong)_ would be that toggling "Only Show Expert Complete" would mark Expert as complete when tomecapped, but leave the module as a whole incomplete if I have other incomplete roulettes. This would be useful for someone who is levelling other jobs via other roulettes but is tomecapped for the week.

Here are some proposed solutions:
1. Keep functionality as-is, but move "Only Show Expert Complete" to a top-level option (which can be toggled on/off regardless of the "Complete When Tomecapped" option. This would effectively produce the result that I had in the final image of my initial post.

2. Keep UI as-is, but make it so that this behavior is observed:
_(For sake of a simple example, let's say that the Duty Roulette module is only tracking Levelling and Expert roulettes)_
![image](https://github.com/user-attachments/assets/37cb3cae-fe3a-4601-8237-1a22a376b2f5)

**Comment by MidoriKami** [comment]
Removed feature in feb4cf2079dde74bafc823df444152970ec664b8
