### ISSUE TITLE
"Color Duty Finder" behaves oddly? Reacts to class-changing with DF window open

### ISSUE THREAD

**Issue by NolanSeryn** [MidoriKami/DailyDuty#215]
I've enabled "Color Duty Finder" for 4 roulettes (Expert, Leveling, Alliance, and Frontlines), but only Expert is ever colored red when  I open Duty Finder:
![image](https://github.com/user-attachments/assets/7786a918-eccc-4699-ba54-73553c788f12)

However, if I change classes while leaving the DF window open, *then* it behaves as expected:
![image](https://github.com/user-attachments/assets/481d7320-21a9-49f8-bce5-ac1c9f6e046b)

Even then, it's not 100% reliable - it seems to swap back to the initial Expert-only state, but currently I can't isolate what causes it.

my config for the Duty Roulette module is as follows:

![image](https://github.com/user-attachments/assets/72df2d5b-3b2b-4be2-8282-5db65d69a88f)

This *could* entirely be an issue on my side only, just wanted to narrow down the cause. Thanks!

**Comment by MidoriKami** [comment]
Unable to reproduce.

**Comment by NolanSeryn** [comment]
Sorry, guess it was just something on my side, then - uninstalling/deleting/reinstalling the plugin seems to have fixed it!

Thanks for letting me know.
