### ISSUE TITLE
Category empty when hiding incomplete module from Todo Display (still)

### ISSUE THREAD

**Issue by Gakai** [MidoriKami/DailyDuty#216]
I didn't get to play the last couple of days, so I could only test it now. The issue described in #207 still persists. I did all my daily tasks except Duty Roulette, and since I have the module enabled, just with "Enable Todo Display" off, the category header does not disappear.

**Comment by MidoriKami** [comment]
Send config files

**Comment by Gakai** [comment]
This is the DailyDuty directory under XIVLauncher/pluginConfigs
[DailyDuty.zip](https://github.com/user-attachments/files/16830475/DailyDuty.zip)

Do you need anything else?
