### ISSUE TITLE
Weird alignment with duty window and custom titles

### ISSUE THREAD

**Issue by Delaene** [MidoriKami/DailyDuty#218]
https://files.catbox.moe/jd52ve.mp4
Seems the window background doesn't like to correctly align with whatever's enabled when using custom category titles.
It seems it behaves strangely until the custom title reaches a specific character length (probably it's the same length as the longest enabled content name)
Video link 
https://files.catbox.moe/jd52ve.mp4

**Comment by MidoriKami** [comment]
This should only be an issue during the modification of the label. Once the element has triggered any kind of refresh it should behave correctly.

I don't really care about a non persistent bug like this at the moment.
