### ISSUE TITLE
[Jumbo Cactpot] Many debug messages and problems with new tickets

### ISSUE THREAD

**Issue by xPumaa** [MidoriKami/DailyDuty#22]
When claiming the rewards, a lot of debug messages are thrown as soon as the MGP amount is revealed, until where the window is closed.
![2022-02-12 23_21_36-FINAL FANTASY XIV](https://user-images.githubusercontent.com/35280763/153731345-09c2d0ae-31f4-4050-81b8-46f5f57d80ee.png)

After this I bought new tickets, but these were not counted down, in addition the next ticket drawing time is negative.
![2022-02-12 23_23_27-FINAL FANTASY XIV](https://user-images.githubusercontent.com/35280763/153731354-6b7ccc02-1f90-4e22-bf6c-240936d3a0c1.png)

**Comment by MidoriKami** [comment]
Fixed in b363303b31555c589ec4f394e64955aacadb9c7d
You'll need to edit the config to remove the three tickets with "CollectedDate" of last week.

**Comment by xPumaa** [comment]
Okay, thanks for the information. I have changed the date values to the correct values one week later and two weeks later respectively.
