### ISSUE TITLE
Wondrous Tails Teleporting with a Book in Inventory

### ISSUE THREAD

**Issue by EdwardShipp** [MidoriKami/DailyDuty#221]
When holding onto a wondrous tails from the previous week, but not having completed it, clicking on the link in the task list starts the teleport to Idylshire to pick up the current weeks book, rather than opening the current book.

**Comment by MidoriKami** [comment]
This is intentional, I don't have a completely reliable way to know if your current book is still valid without doing a lot of work.

So DailyDuty assumes that you should be completing your book in the first week, and thus, if you are on your second week, you need a new book.
