### ISSUE TITLE
[Dailyduty]reset time of jumbo cactpot is incorrect

### ISSUE THREAD

**Issue by Blexymoon** [MidoriKami/DailyDuty#222]
Now jumbo cactpot's reset time is 11pm,but actually it's every saturday 9pm.Even I have 3 tickets but it shows no tickets claimed.
![ffxiv_20241105_161944_183](https://github.com/user-attachments/assets/76aa0856-f3a9-4503-9bb8-573ae72ceb81)

**Comment by MidoriKami** [comment]
Next reset it'll self correct.
