### ISSUE TITLE
Jumbo cactpot resets on Weekly reset day

### ISSUE THREAD

**Issue by Hukinator** [MidoriKami/DailyDuty#224]
Hey, after updating the plugin after patch 7.1 i saw that jumbo cactpot was in the daily duty list. when i interacted with the npc it went away. When the reset happened today it reset again. would like to provide the time from the logs but another plugin spammed the xllog too much for me to find it again.

**Comment by MidoriKami** [comment]
It'll be a while before an update can be released, there are some issues right now with the plugin build system.
