### ISSUE TITLE
[Question / Request] Font for to-do list

### ISSUE THREAD

**Issue by princessoak** [MidoriKami/DailyDuty#225]
Hi, I was wondering; is there currently a way, when customizing the to-do list, to use either a) a custom font - perhaps how some plugins have you add the ttf to plugin's folder or something - or b) have it use dalamud's font (the font set as default through dalamud - mine is a custom font) . 

If not, this would turn into a suggestion, I would really be appreciative if you may consider adding this functionality. It can be tricky for me to read at times, the game's fonts (I assume the ones listed are just the game's) are not my favorite., I also have only one small monitor so I make everything tiny but they are hard to read when you make them tiny.

PS Ty for your work <3 you are appreciated

**Comment by MidoriKami** [comment]
Not possible, the Todo List is rendered into the game layer itself, it's using game code so that it renders below things like your inventory window.

As such it can only use fonts that the game itself uses. It's not possible to use a custom ttf.
