### ISSUE TITLE
Jumbo Cactpot on repeat

### ISSUE THREAD

**Issue by StackBLU** [MidoriKami/DailyDuty#226]
Every few hours, Jumbo Cactpot re-appears as a to-do item. Not sure what causes it.

**Comment by MidoriKami** [comment]
Please ensure you are not using any custom repo plugins, and then reproduce the issue then submit your dalamud.log here

**Comment by trouvien** [comment]
Also having this issue, talking to the Jumbo Cactpot npc temporarily marks it complete but after a bit it still resets itself to "no tickets claimed" status.

**Comment by MidoriKami** [comment]
I still need lots to find the cause.

**Comment by MidoriKami** [comment]
Stale, if more information is provided this issue can be reopend.
