### ISSUE TITLE
Hide Timers When no Objectivs?

### ISSUE THREAD

**Issue by Tjacu** [MidoriKami/DailyDuty#227]
Could we maybe get a checkbox in the settings to hide the Timer bars when there is nothing left to complete in our lists?

Just like Hide during duties, this would be really nice to get rid of them, and also make them pop more when things are up (since once done you can just remove them)

**Comment by MidoriKami** [comment]
I'm not actively playing the game and am not currently accepting feature requests.

You can use chat commands to toggle the timers visible or hidden. `/did help` for a list of commands.
