### ISSUE TITLE
Duty Roulette coloring not working

### ISSUE THREAD

**Issue by submatrix** [MidoriKami/DailyDuty#228]
Seems like in the latest version, the coloring of duties in the Roulette is not working.

![image](https://github.com/user-attachments/assets/ac394fbf-93e8-4476-bed0-8f667c244620)

![image](https://github.com/user-attachments/assets/3c2e2dbf-c88e-4834-a1eb-f6f2f7696436)

**Comment by submatrix** [comment]
This appears to still be broken, unfortunately.

![image](https://github.com/user-attachments/assets/8f2b0f5d-b4c0-4090-8711-3eeab976409e)

**Comment by MidoriKami** [comment]
![image](https://github.com/user-attachments/assets/db9a79e2-5071-4786-9130-b35dc918e71a)
Seems to be working for me?

**Comment by MidoriKami** [comment]
oops, tehe.
fb7cc6e0f0af5df26cef8a2e40a1071adabd27d5

**Comment by submatrix** [comment]
hmm. I updated per your latest update but it's still not reliable. I was able to get the colors to show up once, but after closing the window and opening it up again, it doesn't seem to work anymore.

**Comment by submatrix** [comment]
I updated to the latest version on my other device which I play FFXIV on, and it's definitely still an issue. For example, after updating the plugin, I've opened and reopened the Duty Roulette window 10+ times and I haven't seen the colors working.

Let me know if there's more I can do to help.

**Comment by MidoriKami** [comment]
I'm so insanely confused on why it's only sometimes working... This makes no sense at all. When I reload the plugin it works perfectly, and then all of a sudden it stops working? wtf.

**Comment by MidoriKami** [comment]
@submatrix could you please build and locally test aa629f9539108fdc578ba3ce3e36bd5a8806840c
I'm mostly curious if this causes other tabs to become colored. I only have a ftp account to test with so cant test all categories.

**Comment by submatrix** [comment]
> @submatrix could you please build and locally test [aa629f9](https://github.com/MidoriKami/DailyDuty/commit/aa629f9539108fdc578ba3ce3e36bd5a8806840c) I'm mostly curious if this causes other tabs to become colored. I only have a ftp account to test with so cant test all categories.

Can you provide instructions for how to build locally? Never done plugin development for xivlauncher.

**Comment by submatrix** [comment]
I built the plugin last night using the latest commit and things seem to be working now! Thanks for your diligence.

The other tabs did not get colored, only the Roulette tab.
