### ISSUE TITLE
Showing Wrong Custom Deliverys

### ISSUE THREAD

**Issue by DiggityMan420** [MidoriKami/DailyDuty#23]
i just installed the plugin and its showing the wrong Custom Deliverys Number i  zoned a few times and stays the same See [Pic](https://i.ibb.co/SwsGNvg/Screenshot-8.jpg)

**Comment by xPumaa** [comment]
You have to set the allowances manually when you install the plugin if you have already made the custom deliveries for this week.
The plugin doesn't track deliveries that have already been completed

**Comment by MidoriKami** [comment]
Exactly as xPumaa has stated, it currently only can see turn ins that you have done with the plugin installed. The plugin is still in the early stages of development and improvements will come at a later stage.
