### ISSUE TITLE
[Bug] Spawning into an area considered an instance permanently hides DailyDuty 'Todo List' until a relaunch

### ISSUE THREAD

**Issue by AbstractUmbra** [MidoriKami/DailyDuty#231]
As the title says, lately I've been logging out in my Island Sanctuary, and I've noticed twice now that spawning in these areas and then later leaving doesn't allow DailyDuty to load or render it's small overlay of the todo list.

Not sure what other info to provide, let me know what you need!

**Comment by MidoriKami** [comment]
Duplicate #198
