### ISSUE TITLE
TodoWindow fixed position from bottom

### ISSUE THREAD

**Issue by xPumaa** [MidoriKami/DailyDuty#24]
Is it possible to fix the position of the window from the bottom?

I have the TodoWindow in the bottom right corner. Like this:
![image](https://user-images.githubusercontent.com/35280763/154390460-ba89b133-8891-44a6-9be7-36f5bb9ce90a.png)

So when I do my daily tasks, the size of the window changes and this creates an empty space at the bottom.
![image](https://user-images.githubusercontent.com/35280763/154390687-fc70e9a2-e28a-41ad-954b-14cce7483029.png)

It would be nice if there was an option to resize the window from the top, but I don't know if that is even possible.

**Comment by MidoriKami** [comment]
Eventually, but not anytime soon at all.

**Comment by MidoriKami** [comment]
Initial implementation in 05ab0fe3fb3845b7c83b12ce6155630d37f0da87
Improvements pending in https://github.com/MidoriKami/DailyDuty/pull/33

**Comment by xPumaa** [comment]
It's so simple and I'm so dumb xD
I tried it myself, but I couldn't get the size or the position of the window.

I have always tried to get the size from the current object such as this.Size

**Comment by MidoriKami** [comment]
Ok, tested the feature, and it seems to be working as intended. There might be a sleeping bug that might cause the todo window to crawl upwards, but I haven't been able to reproduce it.
