### ISSUE TITLE
Suggestion: Option for Wonderous Tails to be marked completed when you turned in a book?

### ISSUE THREAD

**Issue by AkiraChisaka** [MidoriKami/DailyDuty#26]
So, currently, your weekly WT is marked as incomplete as long as you are holding a WT book.

However, it's more optimal to only turn in a book when you are able to get a new book.

So usually players only turn in a book once a week.

Can we have an option to mark WT as completed as long as you cannot obtain a new book?

**Comment by MidoriKami** [comment]
The described behavior is not consistent with the programming. Please provide a more specific use case.

Currently it considers the book complete when you get 9 stickers, and will keep the book marked as complete until you turn it in.

**Comment by AkiraChisaka** [comment]
> The described behavior is not consistent with the programming. Please provide a more specific use case.
> 
> Currently it considers the book complete when you get 9 stickers, and will keep the book marked as complete until you turn it in.
> 
> Weekly reset has happened recently, and if you check your book, if it has 9 stickers placed, it should still be marked as complete.

Thanks for the response!

The feature I'm looking for is that once you have obtained a book with 9 stickers, this week's WT is marked as completed even if you turned in the book and obtained a new book.

Basically, since each WT book lasts for 2 weeks, and you can only obtain 1 book a week. If you obtained a book and turned it in immediately on Wednesday, you miss out all the chance for getting lucky stickers when doing other tasks, or rerolling when you have 9 second chance points.

So at least for me, after obtaining a book on week 1, I would wait until week 2 to turn in the book. Then I can obtain the new book on week 2, and wait for week 3 to turn in the book. This way, I will always have a book on me to collect stickers and shuffle for a chance for 3 lines.

I'm mostly looking for a way to make "turning in and obtaining a new book" as the trigger for "I have completed this week's WT".

So an even better trigger would be when your book have been removed once in your inventory, or when the number of stickers on your book have went down (i.e. from 9 to 0), or when the expiration date on the book is in the next week.

Actually is this possible? For the plugin to check the expiration date for the book?

**Comment by MidoriKami** [comment]
If you collect your book on Tuesday, complete all the tasks on Wednesday, then the book will shows as complete (because Stickers == 9).

If you then wait until Wednesday on the following week, your book will still show as complete. 

Then you turn in your book on the second week's Thursday, it will still show as complete until you get a new book.

Once you pick up your new book, it will now show as incomplete.

What about this behavior is inconsistent with what you are requestion?

> Actually is this possible? For the plugin to check the expiration date for the book?
And no, I do not have access to the expiration date of the book.
