### ISSUE TITLE
Duty Roulette across dates

### ISSUE THREAD

**Issue by torakiti2017** [MidoriKami/DailyDuty#37]
Clearing Duty Roulette across dates was not considered digested on the Duty Roulette overlay display.

**Comment by MidoriKami** [comment]
It states very clearly at the top of the module's information block:

```cs
            ImGui.Text("Only detects that you started a duty roulette\n" +
                       "Does not detect successful completion");

            ImGui.TextColored(Colors.SoftRed, "Does not detect completion if started before reset\n" +
                                              "and subsequently completed after reset");
```

Currently there is no reasonable way to determine duty completion reliably.

**Comment by MidoriKami** [comment]
In response to this posted issue, perchbird discovered a way to track duty completions.

https://github.com/MidoriKami/DailyDuty/commit/2eed4451cc05d53ea209edd557c75423b95a07e6

The new build is pending for release on dalamud.
