### ISSUE TITLE
Request - Config options for chatlog notifications

### ISSUE THREAD

**Issue by calli-yama** [MidoriKami/DailyDuty#38]
I'd like to request the option to configure which channel/chatlog box the notifications go to. Not sure about other users, but I use two chat boxes in game: One for FC chats, /tells, /p, etc., and one for generic system messages (commends, instances, exp, etc.)

**Comment by MidoriKami** [comment]
DailyDuty uses the channel specified in the Dalamud settings for output. You can set this to be any chat channel, the default is debug which will show in all tabs.

I will not be adding custom channel support to DailyDuty.

![image](https://user-images.githubusercontent.com/9083275/158946036-d371bf2a-8ff3-4ab7-8e8c-8df980eff646.png)
