### ISSUE TITLE
[Bug] Custom Delivery

### ISSUE THREAD

**Issue by xPumaa** [MidoriKami/DailyDuty#41]
Unfortunately, I don't know how I did it, but my remaining allowances are negative
![image](https://user-images.githubusercontent.com/35280763/159383065-e37100e1-8c92-4f80-acc0-f2762d645e94.png)
[DailyDuty Config](https://github.com/MidoriKami/DailyDuty/files/8319951/DailyDuty.txt)

**Comment by xPumaa** [comment]
I also saw in the config that the reset time for the beast tribes is wrong, but the reset works

**Comment by MidoriKami** [comment]
Without the "how" this information is entirely useless to me =x

**Comment by xPumaa** [comment]
I'm sorry, I just made my custom deliveries and wondered afterwards why the entry is still displayed in red.

**Comment by xPumaa** [comment]
Maybe you should generally make sure that the value cannot fall below zero?

**Comment by MidoriKami** [comment]
This is how it gets set:
https://github.com/MidoriKami/DailyDuty/blob/master/DailyDuty/Addons/SatisfactionSupplyRequestAddonModule.cs#L149

Simply capping it is not the correct fix.

**Comment by xPumaa** [comment]
Yeah, i see
