### ISSUE TITLE
[Bug] Doman Enclave

### ISSUE THREAD

**Issue by xPumaa** [MidoriKami/DailyDuty#42]
In the doman enclave, the settings have negative values.
Unfortunately, I have already donated this week and therefore cannot say which values are saved beforehand.

Or is that the way it is intended?
![image](https://user-images.githubusercontent.com/35280763/159944132-2ff0130a-cdb5-4c13-b16d-c159e8e5b757.png)

**Comment by MidoriKami** [comment]
Ehh, probably fine that's what the game has stored internally and it doesn't enable notifications so I'm not gonna worry about it.

**Comment by MidoriKami** [comment]
I'm not able to reproduce those values 🤔 
Were you in the enclave when you took that pic?

**Comment by xPumaa** [comment]
Sorry for the late reply. I took the pic at the entrance, but it makes no difference.

First I ported there via the aetheryte system, then I deactivated the plugin to reset the data and left the area and finally I activated the plugin again and entered the area again with the same result.

**Comment by MidoriKami** [comment]
Let me know if it persists after weekly reset.

**Comment by AnzeG8** [comment]
Hey, I have the exact same issue. Was hoping the weekly reset would fix it, but no change, still at -25536
Technically it's just a visual annoyance since it still warns on login at reset and shows completed after donating.

**Comment by xPumaa** [comment]
After the weekly reset my config looked like this:
```json
"DomanEnclave": {
  "$type": "DailyDuty.Data.SettingsObjects.Weekly.DomanEnclaveSettings, DailyDuty",
  "DonatedThisWeek": 0,
  "WeeklyAllowance": -25536,
  "NextReset": "2022-04-05T08:00:00Z",
  "Enabled": true,
  "ZoneChangeReminder": false,
  "LoginReminder": true
}
```
_**Outside doman eclave: Plugin disabled > Changed to 40000 > Plugin enabled**_
Everything was fine up to the point where I ported to the doman enclave. The value was set again to -25536

_**Inside doman eclave: Plugin disabled > Changed to 40000 > Plugin enabled**_
The value was already set to -25536 at the start

Is there anything else I can do to help? I have waited to donate for this week in case you want to test something first.

**Comment by MidoriKami** [comment]
Ah sorry wasn't getting notifications on this thread. I found the problem, I was grabbing a signed short from the game. -25536 is actually 40000 unsigned short. 

Fixed in d82725bb8641d46ad90cfd659a7f867ed7ebbd0f

**Comment by MidoriKami** [comment]
I was unable to reproduce because my personal limit is only 20000 and that can't overflow a signed short

**Comment by MidoriKami** [comment]
Visiting the doman enclave with version 1.3.1.2 will correctly save the right values. Sorry for multiple posts on mobile at the moment

**Comment by xPumaa** [comment]
Works perfectly 👍
