### ISSUE TITLE
Combine the Timers and Todo Windows + Add a collapsible toggle

### ISSUE THREAD

**Issue by cglatot** [MidoriKami/DailyDuty#47]
While I really like the redesign of the configuration window, and it is much clearer, it removed one of the best features for me, and that was to have the timers and the todo list in a single collapsible window. Previously I had the DailyDuty config window collapsed at one part of the screen like the following image:

![image](https://user-images.githubusercontent.com/10439257/165927850-560b07b3-6b99-4933-acf1-c6383159a38a.png)

I have commonly used add-ons in that area, and it's useful to have them there for easy access. I don't always want to see their data, but I don't want to have to type chat commands, etc every time I want to open them, so having the collapsible part is really useful.

With this most recent change, it means that I either need to have the timer and duty windows open somewhere, which are unsightly to have all the time, or I need to keep the new DailyDuty config window in the addons, but 1) It no longer shows timers + duties in 1 section, and 2) Because of the new extra-wide config, it now also takes up a lot of space, even when collapsed.

Solution:
What I'd love to see is a toggle (or redesign) to have both the Timers + Todo list in a single window, and give it a collapsible bar so we can hide it when we don't want to see it.

**Comment by MidoriKami** [comment]
Use the actual Todo window and timers window. The command system will be re added soon and you can simply use an in-game macro to toggle them both at once.

**Comment by cglatot** [comment]
Could you at least add collapsible bars to the Todo and Timer Windows? Pretty much every other plugin has each window as being collapsible. To not include them here is a pretty poor UI decision.
