### ISSUE TITLE
Treasure Map Classification

### ISSUE THREAD

**Issue by Evolutious** [MidoriKami/DailyDuty#48]
Good day! Thank you for the most recent update; I love the new layout.

I did notice, however, that when I enable tracking of Treasure Maps, it is putting it in the Weekly Task section on the list instead of the Daily Tasks list as it should be.

![image](https://user-images.githubusercontent.com/49498530/165975795-6c1b31e9-fb29-4656-91b8-5cb7aad1f9f3.png)

**Comment by MidoriKami** [comment]
Fixed already in v2.0.0.1
