### ISSUE TITLE
Commands for timer and task windows

### ISSUE THREAD

**Issue by GerhardBedivere** [MidoriKami/DailyDuty#49]
In previous version just typing /dd in chat would bring up tasks window which was very handy for quick glance on what I still need to do. Would it be possible to create commands for new task and timers windows so I could create macro buttons to bring those up? New windows are clear improvements and are very handy but not needed to be on screen all the time.

**Comment by MidoriKami** [comment]
Planned. New command system will be implemented in a few days.
