### ISSUE TITLE
[Bug] Wondrous Tails chat notifications not working

### ISSUE THREAD

**Issue by AnzeG8** [MidoriKami/DailyDuty#52]
Since the 2.0 update I don't get any chat notifications regarding Wonderous tails. Tried re-enabling every setting and playing with the notifications delay timer in settings to see if this is related with no luck. All other chat notifications work fine.
Let me know if I can provide any logs/tests from my side that would help.

**Comment by MidoriKami** [comment]
The only chat notifications for Wondrous Tails are when you enter or leave a duty.

**Comment by AnzeG8** [comment]
> 

Yes, I don't get ANY notifications, at any point

**Comment by MidoriKami** [comment]
Send your character configuration file `XIVLauncher\pluginConfigs\DailyDuty` Send the file for the specific character in question.

**Comment by AnzeG8** [comment]
[18014498561357528.zip](https://github.com/MidoriKami/DailyDuty/files/8609756/18014498561357528.zip)

**Comment by MidoriKami** [comment]
Alright I'll take a look tomorrow

**Comment by erickt420** [comment]
I'm getting the log-in notifications, but when I enter a duty for which I can get a stamp, or a duty which I can re-roll for a stamp (most useful feature ever!!!), I am no longer seeing the notifications from this plugin. This is seriously the best plugin ever though thank you so much for creating it.

**Comment by MidoriKami** [comment]
I need so more specific information, it is any duty? Specific duties? Specific categories? Please describe the sequence of events before entering the duty, and the sequence of events after leaving the duty, including where you are queuing for the duty from.

**Comment by MidoriKami** [comment]
Also please send "DailyDuty.json" located in PluginConfigs

**Comment by AnzeG8** [comment]
>I need so more specific information, it is any duty? Specific duties? Specific categories? Please describe the sequence of events before entering the duty, and the sequence of events after leaving the duty, including where you are queuing for the duty from.

It's any duty from anywhere. I get no text output about wondrous tails at any point. Most of my queuing would have been from Idlyshire after picking up the book, I did the Doman enclave just before that. Next day expert roulette would have been right after login I suppose, from Gridania.
Here's what I did:
- 2.0 update to DD, I go through and turn on all the stuff I had turned on before
- weekly reset hits a few days later, on login I get notification about Doman enclave, but not about a new book available
- pick up new book, start doing unsync solo extremes to get some easy stamps. Duty finder overlay and links all work fine, but no 'stamp available from this instance' at any point. Not on entry, finish, or exit.
- Do expert roulette, still no notifications
- Next day: no reroll notification for expert, no 7 stickers reroll warning
- Finish the book, turn it in, DD marks as complete so it seems to be tracking internally, just no text output

I've tried to toggle the settings on/off a few times during this, but no change to anything.

**Comment by AnzeG8** [comment]
[DailyDuty.zip](https://github.com/MidoriKami/DailyDuty/files/8638035/DailyDuty.zip)

**Comment by MidoriKami** [comment]
New book, and 7 stickers rerolls we're removed in 2.0 btw. I have some things I need to figure out before I reimplement them because it did t quite work how I wanted it to.

**Comment by MidoriKami** [comment]
Is this issue still happening with version 2.0.2.3? If so please provide logs again, I added additional Wondrous Tails logging to v2.0.2.3

**Comment by AnzeG8** [comment]
I'll try again on reset when I get the next book to test with and let you know

**Comment by MidoriKami** [comment]
So a brief explanation, since I removed the other types of notifications from Wondrous Tails, I also removed the zone change notification toggle, but not until after I had enabled it in my test build. So my config has that enabled.

Well, the generic code I use for zone change required zone change notifications to be enabled to see the duty start or end notifications or else it won't send it. The manual fix is to edit your character config, find Wondrous Tails and find ZoneChangeNotification and set it to true and save it while the game or plugin isn't running.

**Comment by xPumaa** [comment]
If you wait a bit for the next update to be available, you can also deactivate and reactivate the "Duty Start/End Notification" option in the WondrousTails options to fix this bug.
Then it doesn't have to be edited manually via character config
