### ISSUE TITLE
[Feature Request] Collapsible Todo Window

### ISSUE THREAD

**Issue by lsequeiraa** [MidoriKami/DailyDuty#53]
If there's one thing I miss from the previous version is being able to collapse the todo list.
While I love the option to remind myself of what's missing, having the todo list constantly looking back at me can be daunting.

Personally, I love the option to collapse at will, to check what's missing and what not.
Would love if the new todo window could also support this.

**Comment by MidoriKami** [comment]
Why is the command system insufficient to achieve this? You can make an in-game macro with the command `/dd todo toggle` to show and hide the window, same applies to the timers window.

**Comment by lsequeiraa** [comment]
I guess it's the same thing as asking why would a person not save to favorites and close the browser tab and instead leave it open indefinitely.
The result is the same, yes, it's just the way you do it.

This to say, it was how I got used to use the plugin.
I guess I could change the way I use the plugin, and if my request is more work than it's worth, I guess I will.

**Comment by MidoriKami** [comment]
The todo window didn't have a collapsible header in the last version, I don't understand what you are referring to then.
Are you referring to the main window?

**Comment by lsequeiraa** [comment]
Well, maybe it was my bad usage of the plugin, but the main window was in fact the todo windows on the previous version, right? It was simply a tab on the main window. And said main window was collapsible.

Nowadays, while you have the list of todo stuff in the main window, it includes everything, not just what you enabled. That list of enabled stuff was relegated to the new todo window.

**Comment by MidoriKami** [comment]
This just gave me a idea, look forward to the next release.
