### ISSUE TITLE
Game is crashing to desktop with no errors when opening plugin

### ISSUE THREAD

**Issue by distraughtklownz** [MidoriKami/DailyDuty#57]
The game will load in and work without any issues. As soon as I type /dd to chat, the game will not load the plugin and immediately crashes to the desktop.

**Comment by MidoriKami** [comment]
Is this with version 2.0.2.x? That update was to address this issue.

**Comment by distraughtklownz** [comment]
Yes, I even uninstalled the addon completely and then reinstalled it.

**Comment by MidoriKami** [comment]
Reproduce the crash, then send the dalamud.log file, send the dailyduty.json file in plugin configs, and send the contents of the DailyDuty folder in plugin configs.

**Comment by MidoriKami** [comment]
Without more information or confirmation that this is still happening in v2.0.2.3+ I'll be closing this issue in 24hrs

**Comment by distraughtklownz** [comment]
Sorry for not responding sooner. What ended up resolving this for me was going into "\\AppData\Roaming\XIVLauncher\installedPlugins" and manually removing the plugin and then reinstalling it from scratch. Everything has been fine since then.
