### ISSUE TITLE
A slight typo in the Hunts chat notification

### ISSUE THREAD

**Issue by rdowers** [MidoriKami/DailyDuty#69]
This is incredibly low-priority, but just for the sake of completeness:

[21:19][DailyDuty] [Hunt Marks (Weekly)] 1 Hunts Remaining

That should be "Hunt", not "Hunts". Or if you don't want to create special coding just for when there's 1 hunt remaining, "Hunts Remaining: 1" would be easier. :)

**Comment by MidoriKami** [comment]
English suuuuucks.

I'll fix it
