### ISSUE TITLE
Teleporter integration?

### ISSUE THREAD

**Issue by chitinlink** [MidoriKami/DailyDuty#7]
Would be nice if you could just click in chat or the plugin window to be teleported where you need to go.

**Comment by MidoriKami** [comment]
Please elaborate, when how and where would you want to teleport with DailyDuty?

**Comment by chitinlink** [comment]
For instance, when I get my message about Mini Cactpot, that message could have a clickable link that teleports me to the Gold Saucer.
For Wondrous Tails to Idyllshire. For deliveries it would go to the nearest available aetheryte.

**Comment by MidoriKami** [comment]
The MiniCactpot/JumboCactpot ones are good idea.

I disagree about Wondrous tails, being notified to teleport to Idyleshire each time you login or join a sticker duty would be confusing for many.

Custom Deliveries can be unlocked in several different places, and there are advantages and disadvantages to turning in items at different NPC's, there's no definitive "go here", unlike for MiniCactpot/JumboCactpot/FashionReport.

**Comment by MidoriKami** [comment]
> You don't have to notify people to teleport to Idyllshire, just have the button in the UI teleport you to Idyllshire.
> 
> Additionally, for maps, you could teleport people to Ultima Thule (Base Omicron). If you really want to do it well you could get the highest gatherer level and teleport based on that.


There's already a teleport to Idyleshire button in the games teleport UI. I see no reason to add a redundant button.

I personally use wotsit for teleporting to places like that.

I will not be doing any kind of teleport decisions for treasure maps. That gets too close to automation for my preferences.

**Comment by MidoriKami** [comment]
Added in 144a937c80e6a6b55daf3cfd6ecd27255f9e3522
