### ISSUE TITLE
Leve timer showing wrong time

### ISSUE THREAD

**Issue by PrincessRTFM** [MidoriKami/DailyDuty#72]
My vanilla leve allowance timer shows [a little over eleven hours](https://user-images.githubusercontent.com/8753564/170701578-c018fbe6-e70c-4cc1-a2f0-e733d5de26a6.png) until my next allowance increase. My DailyDuty timers window shows [a little over twenty three hours](https://user-images.githubusercontent.com/8753564/170701686-ccaa6bba-d600-455b-b12b-4d5de1ec2dbb.png) instead.

**Comment by MidoriKami** [comment]
Ah, simple error, leve allowances are allocated every 12 hours, not every 24 hours, so it's looking for the first of the days two resets.

This doesn't impact the logic, only the displayed time.

DailyDuty extracts the number of leveallowances directly from the game every time you view the count.
