### ISSUE TITLE
new 6.15 Custom Deliveries

### ISSUE THREAD

**Issue by gurkburk76** [MidoriKami/DailyDuty#74]
Hello, lovely plugin, could support for the new 6.15 Custom Deliveries be added in ?
https://na.finalfantasyxiv.com/lodestone/topics/detail/91ca242abdbf0750db28d01f4f38d27c3aea617b

**Comment by xPumaa** [comment]
What do you mean by adding the 6.15 Custom Deliveries?
The custom deliveries are already added. There is no need to add the new deliveries as the task works with the remaining allowances.

**Comment by gurkburk76** [comment]
Ok that's odd, for some reason i did not track/unchecked it from the list when i did it, how can i troubleshoot ?

**Comment by gurkburk76** [comment]
Oh that's where you pull info from, i'm sorry i didn't realise that i actually have 6 left. Closing post :)
