### ISSUE TITLE
Rename 'Beast Tribe' to 'Tribal Quests'

### ISSUE THREAD

**Issue by flatluigi** [MidoriKami/DailyDuty#83]
The game's deprecated the term for several reasons as it doesn't really fit where the game's gone since launch, and I would like to see the change carry over to this addon as well.

**Comment by MidoriKami** [comment]
Due to the playerbase being not sufficiently aware of this change I will not be updating the name for several weeks.

No matter which action I choose people will complain. The name will stay as-is for the time being.
