### ISSUE TITLE
QOL: Remove Timers hint if timers are enabled

### ISSUE THREAD

**Issue by TheGokki** [MidoriKami/DailyDuty#84]
I have timers enabled, but they are all complete (and hidden). When i complete all, this yellow messages shows up again. Is it possible to keep it hidden?

![image](https://user-images.githubusercontent.com/87334024/187918024-f27154b9-cc20-4c5e-9c8e-89220cee57f6.png)

**Comment by MidoriKami** [comment]
Nice catch, thanks for the report.

**Comment by MidoriKami** [comment]
Fixed in a4dfbd0738073887ea84f8d4aa31b81ac1b42faa
