### ISSUE TITLE
Feature Request: Daily/Weekly Reset Timers

### ISSUE THREAD

**Issue by iwantcookiesnow** [MidoriKami/DailyDuty#85]
There used to be countdown timers until the next daily/weekly reset in an older version of the plugin, but now they're either gone or I simply can't find them anymore. 
General timers like those were useful for some untrackable tasks (e.g., how much time is left to complete the current unreal trial), and they also served as a reminder for when all the completed tasks would reset and become available again.
I miss this feature and would very much appreciate to have it back. Thanks.

**Comment by MidoriKami** [comment]
You can rename any timer to "Daily" or "Weekly"
