### ISSUE TITLE
">n days" style if there's more than one day left on TimerStyle

### ISSUE THREAD

**Issue by pigsflew** [MidoriKami/DailyDuty#87]
I'd love for the timer to be, really, just the info I need, which is:

>= 1 day: `$d' day(s)'`
>= 1 hour: `H:MM` (no need to zero-pad the hours)
>= 1 minute: `MM \m`
else: `<1m`

that way the label would be a lot easier to read without being lengthy. I don't know if that's easy with the way the C# TimeSpan formatter works?

**Comment by MidoriKami** [comment]
It's mostly a matter of overloading the user with options. The current implementation follows ISO standards

**Comment by pigsflew** [comment]
Yeh, it's a little ugly to me but not a huge issue, I just wondered if something like this would be doable to implement as a "Human" style option

**Comment by MidoriKami** [comment]
The actual display code is here:
https://github.com/MidoriKami/DailyDuty/blob/master/DailyDuty/UserInterface/Windows/TimersOverlayWindow.cs#L220

The timer options are here:
https://github.com/MidoriKami/DailyDuty/blob/master/DailyDuty/Configuration/Components/TimerSettings.cs

At the moment I can't picture an elegant solution to the proposed problem, but if a PR was presented that tackles this issue in a somewhat elegant way I would accept the PR.

**Comment by MidoriKami** [comment]
Closing issue for now, unless a reasonable way to implement crops up this will stay as a #wontfix
