### ISSUE TITLE
Bug: buttons not fully visible with Dalamud font size is too large

### ISSUE THREAD

**Issue by jguluarte** [MidoriKami/DailyDuty#88]
I have my dalamud visual scaling set to 36pt (large 4k tv), and it makes some sections of the window not visible, such as the buttons in the lower left section of the main DailyDuty window

**Reproduction Steps:**
1. Set Dalamud font size to 36pt
2. Open `/dd` menu
3. Observe the buttons in the lower left area are clipped "under" the bottom of the window

**Comment by MidoriKami** [comment]
Very nice instructions for reproduction thank you.

**Comment by jguluarte** [comment]
I'm also an engineer ;) I figured it would make your life easier haha
