### ISSUE TITLE
[Question / Conversation / Possible feature request ]

### ISSUE THREAD

**Issue by jguluarte** [MidoriKami/DailyDuty#92]
# Preface
I would normally send some kind of message or DM -- but I wasn't able to find another way of contacting you through some other social profile. I really adore this plugin, it has become one of the most useful tools for me, I greatly appreciate _how amazingly responsive_ you've been to the bugs that I've reported -- you fixed them with a sub-24h turnaround time!!

## Background
I'm also a software engineer and have been for ~17 years. If this is something that you think could be a good idea, I am willing to contribute some time and effort to bring this idea to life :)

# Idea
I know after reading your [issue README](https://github.com/MidoriKami/DailyDuty/issues/9) that you aren't going to be duplicating any work in other mods.

What if instead, a hook is added to allow another mod to register a TODO notification?

## My specific use case idea
I love how clearly the TODO list in `DailyDuty` tells me when I have something to do. It would be amazing if [Accountant](https://github.com/Ottermandias/Accountant) could add a daily task to say `Squadrons`, or `Plot: Old World Fig`, or `Ventures`. It does a great job at tracking them, but it doesn't do a great job at reminding me.

## Collaboration
If you like this idea, I can go talk with the author of `Accountant` to see what they think, and similarly offer to them to add this feature on that side. If both of you like the idea and greenlight it, I'll also make sure to add another README to this plugin for other authors who might also want to do this. It would also follow my usual professional approach: research, proposal, discussion, code reviews, etc.

**Comment by MidoriKami** [comment]
First step would be joining the discord that myself and other dalamud plugin devs use. https://goat.place/
