### ISSUE TITLE
Change "Beast Tribe" to "Tribal Quests" 

### ISSUE THREAD

**Issue by Contrastellar** [MidoriKami/DailyDuty#94]
Hi! Really love this mod and would love to help contribute in my own small little way. 

I noticed that the language for the mod uses the now deprecated "Beast Tribe", and decided to make the small edit in [my own fork](https://github.com/Contrastellar/DailyDuty/commit/88cba3b541fec1a4154706dbe5790404a291195e). I figure this is a fair edit, just because it reflects the language used in game, and going forward.

These changes are only done in the localization json file -- so it shouldn't break anything as far as I can tell.

Let me know if you'd like a PR made sooner rather than later! Thank you!

**Comment by MidoriKami** [comment]
See #83

**Comment by Contrastellar** [comment]
Ah, I should've done a search. Thank you for the rapid response! ^^

**Comment by MidoriKami** [comment]
In a few more weeks I will be willing to accept a PR to change the wording, however, I want the code to reflect the change too, so the internal classes would get renamed at the same time.

**Comment by Contrastellar** [comment]
That makes a lot of sense! Thank you for clarifying and keeping this mod updated!

**Comment by MidoriKami** [comment]
This issue is now eligible for completion. Feel free to PR changes
