### ISSUE TITLE
A Bug about JumboCactpot

### ISSUE THREAD

**Issue by yumozzz** [MidoriKami/DailyDuty#98]
I find that JumboCactpot weekly duty can't be normally marked finished. It seems that it's NextReset value is wrong for some unknown reasons:
![image](https://user-images.githubusercontent.com/98417370/215272480-c0688cd3-b7d5-4e0e-8bbf-528bc7289e63.png)
I'm unable to suppress the notification by the suppression button (looks like the Next Drawing countdown will automatically reset to zero when reaching -60 secs and the suppress status will be reset shortly after I click the button) or reopen the JumboCactpot window in-game or reopen the game itself. This bug just pops out when I finish JumboCactpot as usual, and I have no idea on how to reproduce it or fix it. The other functions work fine.

**Comment by MidoriKami** [comment]
In-game use the command `/xllog` and change the log level to `Debug`.
Log-out and then back into your character and send me you `dalamud.log`

![image](https://user-images.githubusercontent.com/9083275/215285223-927d4285-0c94-4cdf-88da-013ab537f91a.png)

Attach a copy of your character config.

**Comment by yumozzz** [comment]
[dalamud.log](https://github.com/MidoriKami/DailyDuty/files/10528053/dalamud.log)
[19014409514412264.txt](https://github.com/MidoriKami/DailyDuty/files/10528056/19014409514412264.txt)

**Comment by yumozzz** [comment]
The second file is the config generated by the plugin.

**Comment by yumozzz** [comment]
Sorry I forget to logout, but the log content turns out to be the same even if I close and reopen the game.

**Comment by MidoriKami** [comment]
You are not on the current version of DailyDuty, please update.

**Comment by MidoriKami** [comment]
I do not provide support for Dalamud_CN plugins.

**Comment by yumozzz** [comment]
It seems that Dalamud CN can't get the latest version of some plugins, I'll try to compile the plugin. Thanks for your help.
